### ISSUE TITLE
Missing item on Anub'arak's loot table - Azjol-Nerub Heroic

### ISSUE THREAD

**Issue by Urdroch** [dalaranwow/dalaran-wow#1537]
Nothing game breaking, but the Jewelcrafting design for  http://wowpedia.org/Infused_Twilight_Opal does not drop from Anub'arak in the Azjol-Nerub Heroic mode instance.

Various databases (websites, atlasloot etc.) confirm that the design should be available at this patch. It's possible that the problem stemmed from the fact that later on (Cataclysm) the gem and design were removed altogether from the game and replaced by another gem/design, which is what several up-to-date databases currently show.

**Comment by priory** [comment]
I ran it over 30 times just for that design. And i've played 1 year without anyone having it nor seen it dropped.

**Comment by Rushor** [comment]
DB/Item: Add 'Design: Purified Twilight Opal' for Anub'arak in the Azjol-Nerub Heroic mode

* closes https://github.com/dalaranwow/dalaran-wow/issues/1537
* commit: 13fd9eb534c20969661f59e3d3799c78827d47c2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ErasmusHereticus** [comment]
It is shameful at best that after nearly 4 years this issue hasn't been resolved yet. As of writing (January 23rd 2018) this item still does not appear in Anub'arak's loot table on the live server.

So obtaining all Jewelcrafting recipes is flat out impossible, even now.

**Comment by ErasmusHereticus** [comment]
Still nothing on live.

**Comment by Lothloryen** [comment]
Thank you for the reminder.

**Comment by Derolana** [comment]
The jc cut drops now.. but 4 times im doing it and epic item doesnt drop, only blue. So I think instead of epic item the jc cut will drop, always
