### ISSUE TITLE
[Priest][Levitate]Channeling spells being interrupted while floating

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1672]
If you use mind flay or penance while having levitate, the channeling will be interrupted. 

Does not interrupt Divine Hymn or Hymn of Hope.

**Comment by Rushor** [comment]
Core/Entities: don't absolute compare positions on UpdatePosition

* closes https://github.com/dalaranwow/dalaran-wow/issues/1672
* commit: 5588718eda8cc443068d21ebfa5fa3a19e35ff94

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After few tests on PTR this:

> If you use mind flay or penance while having levitate, the channeling will be interrupted.

is still an issue.

Short video demonstation:
https://www.youtube.com/watch?v=NqY4ibj2ON0&feature=youtu.be
