### ISSUE TITLE
[Quest] Misplaced quest: Botanist Taerix

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1962]
http://www.wowhead.com/quest=9371/

This is a simple breadcrumb quest in which **Proenitus** (http://www.wowhead.com/npc=16477) asks you to meet **Botanist Taerix** (http://www.wowhead.com/npc=16514) to do science stuff with her.

It should be offered only after the _Urgent Delivery!_ (http://www.wowhead.com/quest=9409) is completed. Quoting wowhead:

"This quest isn't offered until you've completed Urgent Delivery! Given that the follow up to this breadcrumb quest is available earlier, this one's fairly easy to miss."

Currently you can take it right after _Replenishing the Healing Crystals_ (both versions: http://www.wowhead.com/quest=9280, http://www.wowhead.com/quest=9369) instead, which shouldn't be the case. 

Also, _Botanist Taerix_ should be on auto-accept, which isn't the case right now since because Proenitus' quest order is messed up, he often offers two quests at once (he only should offer one quest at the time normally).

**Comment by Rushor** [comment]
fixed with:

DB/Quest: Urgent Delivery! - Update prequestorder

* closes https://github.com/dalaranwow/dalaran-wow/issues/1944
* commit: 6773dab5d32a0920bbc61743d97c780fd6a2e10e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
This is not on ptr or the fix doesn't work as the issue remains the same as @n-ghost described it.
