### ISSUE TITLE
[Ulduar][Achievement] Dwarfageddon

### ISSUE THREAD

**Issue by Dupsi** [dalaranwow/dalaran-wow#1990]
Wowhead Link of the Achievement: http://www.wowhead.com/achievement=3097/dwarfageddon-10-player
Example solo Video: http://www.youtube.com/watch?v=U6YXKl2resI

How it should work: Upon killing the first "Steelforged Defender" the Achievement timer should start counting, upon reaching 100 within a 10 second window the Achievement should pop up.

How it currently works: Upon killing the first "Steelforged Defender" the counter does not start counting towards the Achievement criteria and the Achievement will not pop up.

**Comment by Rushor** [comment]
Scripts/Ulduar: Implement Achievement: Dwarfageddon

* closes https://github.com/dalaranwow/dalaran-wow/issues/1990
* commit: 3a75da7121e2fd46739432f86fdead3415a682b2

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ondrakrat** [comment]
Still not working - tested it today in the 25 player version. The counter does not even start, just like as stated above.
