### ISSUE TITLE
[Item] Titanium Seal of Dalaran reward from Achievment [The Coin Master]

### ISSUE THREAD

**Issue by Goodoldbloke** [dalaranwow/dalaran-wow#2086]
The coin doesnt work correctly.
The graphic of throwing the coin works but it doesnt land on either Heads or Tails.
People spend hours trying to get this, the dissapointment is big.
http://www.wowhead.com/item=44430/titanium-seal-of-dalaran

**Comment by M0dinstaller** [comment]
I can confirm this, and as Magohoy said, the disappointment is big.

**Comment by bonethugmono** [comment]
I can confirm this as well, the disappointment is huge, like other things in my pockets.

**Comment by Portotada** [comment]
-.- i guess i have to check the bugtracker everytime before attempting any other broken achievement or quest.
I could have gotten alot of gold if i was going to fish. and instead i have a useless coin.

**Comment by Rushor** [comment]
Scripts/Spells: Implement Titanium Seal of Dalaran

* closes https://github.com/dalaranwow/dalaran-wow/issues/2086
* commit: 044a4c1dd4e103b13f79226c2bffb31dab88080f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ErasmusHereticus** [comment]
The item is still broken on the live server.

It's pitiful that at least some of the current expansion vanity items don't even work correctly.

**Comment by Portotada** [comment]
Yes it still doesnt work :|

**Comment by BanditofBandwidth** [comment]
2019. Still doesn't work.

Got the coin after all the fishing needed to get it.
I can right-click it and it makes the soundeffect, 

but it does not show the text in the chat.
Disappointing after the time put in it to get it.

**Comment by Jeraimee** [comment]
I've just tried this item again and it's still not working. This seems like it's been fixed someplace already back in 2016 but that is not the case. Please re-open.
