### ISSUE TITLE
[Ulduar] Stuck in Combat with Hodir

### ISSUE THREAD

**Issue by delebota** [dalaranwow/dalaran-wow#2087]
We have had this issue twice now. If you kill Hodir while Flash Freeze is active you become stuck in combat with him. Anyone who dies, hearths, alt-f4s, etc. will not be able to re-enter the instance for over an hour until it fixes itself.

**Comment by ashido96** [comment]
Flash Freeze from hodir freezes all the spectators in thorim's room, however that mite contribute to the issue.

**Comment by Lothloryen** [comment]
Hello there,

The issue with the combat bug and not being able to zone in under certain circumstances after killing Hodir should now be solved - if anyone experience this problem again, please give feedback below and provide as much details as you can, it will be really appreciated.

Thank you very much.

**Comment by LoveDalaranWow** [comment]
This bug is still a thing, currently we have a 10m group stuck outside Ulduar since yesterday's night since we killed Hodir (unable to zone while an encounter is in progress).

**Comment by LoveDalaranWow** [comment]
Update: Impreza came and tried to see what happened, we had everyone outside the instance and none logged of while in the raid and inside the instance. He just logged off and we are still stuck outside.

**Comment by robinsch** [comment]
@Lothloryen

**Comment by LoveDalaranWow** [comment]
We managed to enter after 1+ hour of wait today, the bug is still a thing.
Just pointing out that having GMs answering "you have to wait for 30 minutes hope you didn't pug it eheh" it's kinda unprofessional.

**Comment by ImprezaWoW** [comment]
Hello again. Sorry if you felt that it was unprofessional - but I said that when someone who's not from the raid group goes offline in the instance, others can not enter. Also I said that it bugs out but 30 minutes is usually enough for a soft reset. Besides those 2 cases there's nothing I can do anyways. I'll make sure to not put smiley faces next time if it makes you feel uncomforable. Cheers.

**Comment by Lothloryen** [comment]
Hello there,

If you could please explain in detail the circumstances of your Hodir kill, it might help me finding the source of this issue.

**Comment by LoveDalaranWow** [comment]
We killed him right after a Flash Freeze (we were aware of the combat bug happening if you kill during the casting of the spell), iI'd say like 15 seconds after he froze the people.
The moment we killed him there were a couple of Flash Freezes still alive, probably it might have been that.
Also I noticed that the very moment we killed Hodir he got around 3-4k hp back and started looking at the tank as if he was just taunted, so probably might have been one of those two causing the bug.
We had a couple people dead by the time we killed Hodir, with one shaman's reincarnation used and one druid's rebirth used during the fight.  The fight took around 4 minutes overall, and we had to send in the warlock's pet in the beginning (before the actual pull) to have the flash freezes "debugging" and resetting as intended.

**Comment by PolarCookie** [comment]
Flash freeze still hits the spectators

**Comment by saltylopez** [comment]
Happened to us twice this week, once in our 25 man and again in our 10 man.  I can't recall how it happened in 25 man but in 10 man we killed him as he was still channeling flash freeze.  His exit door opened and his chest was accessible, but his entrance door stayed closed.  We dropped out of combat, but if anybody left the zone for any reason, they were unable to return "cannot zone in while an encounter is in progress".

This is a huge issue for raids that have a limited time to do Ulduar.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much, I will work on it during the next few days and deploy a correction as soon as I can. Really appreciated the feedback.

**Comment by Rushor** [comment]
Scripts/Ulduar: Hodir - Remove combat for all player on the map after death

* updates https://github.com/dalaranwow/dalaran-wow/issues/2087
* commit: 47c5a1ddbfb1389e4b0a8aa1e1610c843ae8ceb1

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Haleorn** [comment]
Just encountered this issue with Alliance raid ID 1683. We're fairly sure flash freeze was up right near the end/when we killed him - we only fully realised there was a problem later after wiping on Thorim. As I write this our PUG raid is still waiting another few minutes, clinging to hope of the rumour that it might soft reset. I deeply suspect it represents the end of our attempt though, pls fixeroni. :(

**Comment by Guzzone** [comment]
Just here to say this bug is still a thing and isn't fixed.
In 2 of the 3 Ulduar 25 men I did in the last month (since I started hosting them basically) Hodir bugged and I couldn't get people back in after his kill saying an encounter was in progress, additionally today we did him as the last keeper (because of this) and vezax's door didn't open.
I didn't really notice after how much we killed Hodir since Flash Freeze but I'm pretty sure flash freeze is still hitting Thorim's arena spectators.

**Comment by Lothloryen** [comment]
Hello there,

I have deployed a fix with a different approach (already on Algalon). If you experience it again, write an ingame ticket, please, we have now some tools in order to try to identify the source of the combat bugs on real time.
