### ISSUE TITLE
Dungeon Finder lv 60-68 issue

### ISSUE THREAD

**Issue by Cone182** [dalaranwow/dalaran-wow#2157]
What is the problem?
- The dungeon finder calls people in the dungeon called The Escape From Durnholde, this dungeon is available from lvl 64-73, but when it calls in players under lvl 66, the dungeon finder says, that you cant get into that dungeon only if you are lvl 66 or above. This thing happened many times when we had a player under lvl 66 in our party, during my leveling.

How it should work?
- Players under lvl 66 but above 64 should be able to enter the dungeon using the Dungeon finder.

**Comment by belegija** [comment]
confirmed. still an issue. we had to kick several people which could not get in

**Comment by Golganeth** [comment]
Level required must be adjusted on the RDF feature and increased to 66. Quest requirements condition must be added;

> In order to be able to access this first instance in the Caverns of Time, the player must be level 66 and complete the quest To The Master's Lair from Steward of Time, and then the other quest The Caverns of Time from Andormu.

> Advised level 	66-68

**Comment by Rushor** [comment]
DB/Access Requirement: Caverns Of Time, Old Hillsbrad Foothills needs quest "The Caverns of Time" to be completed

* closes https://github.com/dalaranwow/dalaran-wow/issues/2157
* commit: 9977c4efac5552749a59e0eb9d8b5560aa5a776d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ImprezaWoW** [comment]
Ping! Players still get Old Hillsbrad Foothills from RDF even though they're under level 66, thus they are unable to enter. @Lothloryen
