### ISSUE TITLE
[Horde Quest] Containing the Rot - Item drop rate bugged

### ISSUE THREAD

**Issue by GCatalinStefan** [dalaranwow/dalaran-wow#2174]
So,

I've been farming this "Rot Resistant Organ" for the quest "Containing the Rot" for a few good days already. I killed over 1000 mobs, yet it didn't drop...

In this reference it says it is a %3 drop rate, which takes 33-34 creeps for a %100 chance.

 Here is the link of the item: http://www.wowhead.com/item=36800
Here is the link to the quest: http://www.wowhead.com/quest=12100

**Comment by GCatalinStefan** [comment]
Bump!

1500 mobs, no organ yet ....

**Comment by ctroller** [comment]
That's not really how drop chances work (you aren't guaranteed a 100% drop after x*P kills, in that case 33.3*0.03), but if you really killed 1000 of those mobs i agree that something either has to be bugged, or you're simply killing the wrong mobs. I remember back when i was leveling it took about 100 kills, which is also a lot more than you'd expect

**Comment by GCatalinStefan** [comment]
I actually killed only bears and elks since they are the only mobs in that zone, near the nerubian instances ground entrance.

**Comment by deltafoxnine** [comment]
I got it after like 100 kills

**Comment by aepoirier** [comment]
As of Oct. 7, 2015 this bug has remained unchanged. My guild mate and I killed well over 150 mobs, with no drop for Rot Resistant Organ for either of us.
http://www.wowhead.com/quest=12100/containing-the-rot
Comments regarding drop rates are mostly posted from patches 2.4.3 - 3.0.3 and there seems to be a consensus that the organ should have a significantly higher drop rate (most commenters received the organ within the first 15 kills to complete part 1 of this quest).

**Comment by Golganeth** [comment]
Fixed with the new loot system.

**Comment by Mattgoheels** [comment]
This is not fixed.  I have killed well over 100 mobs and no drop.

**Comment by Rushor** [comment]
Open a new issue please
