### ISSUE TITLE
[Hunter] Raptor Strike (can disable melee attacks)

### ISSUE THREAD

**Issue by Max0r847** [dalaranwow/dalaran-wow#2281]
**Raptor Strike** - _2973_

It is possible for **Raptor Strike** _(ID: 2973)_  to cause a situation in which the hunter is _no longer able to perform any melee attacks_ whatsoever, including auto-swings, until relogging.

---

**How To Reproduce This Bug**
1. Aggro a mob in a world zone (not dungeon)
2. Run away from the mob until it begins to retreat back to its original position
3. While continuing to target the retreating mob, spam **Raptor Strike** _(ID: 2973)_

**Results**
1. Attempt to melee attack any mob, you will see that no attacks will occur
2. You will notice that any mob you click on, even if it's a normal default left click to select without attacking, your hunter will automatically begin to try to cast **Auto Shot** _(ID: 75)_
3. If you get out of line of sight of the mob while still in range to shoot it, you will notice that your hunter repeatedly tries to cast **Auto Shot** _(ID: 75)_ on it as if spamming a key that is bound to it
4. This bug does not go away until you relog. Reloading does not fix it.

---

**Why This Is A Problem**

Personally I like to macro **Raptor Strike** _(ID: 2973)_ into my ranged attacks in case I get within melee range before, during or soon after casting my shot. This allows me to do more overall damage more quickly and easily in situations where I go into and out of melee range.

The problem occurs when spamming my shots on a target and having it suddenly retreat, perhaps because I pulled it back too far while kiting it. If **Raptor Strike** _(ID: 2973)_ is macroed into those shots, melee gets disabled due to this bug.

I've even had mobs retreat from me while I was in melee range and attempting to kite, and spamming **Raptor Strike** _(ID: 2973)_ itself.

For the average hunter player this may seem trivial, but to the enthusiast who tweaks everything for maximum performance this can be quite a let-down.

---

**Makeshift Solution**

I've been told by another who tested this that casting **Feign Death** _(ID: 5384)_ fixes this and allows the hunter to melee again. However this is unsatisfactory for low level hunters that cannot **Feign Death** _(ID: 5384)_ yet (the hunter I discovered this problem with is level 7), and it forces **Feign Death** _(ID: 5384)_ into cooldown when the problem occurs, leaving it unavailable for other purposes that may come up in the interim.

---

http://wotlk.openwow.com/spell=2973
http://wotlk.openwow.com/spell=75
http://wotlk.openwow.com/spell=5384

---

Sorry, I seem to be unable to apply labels to this report. It seems I require a paid account to do this. Perhaps in the future.

**Comment by carlosoharo** [comment]
still happening, fix it please

**Comment by Rushor** [comment]
related: https://github.com/TrinityCore/TrinityCore/issues/13595

**Comment by Max0r847** [comment]
So I just confirmed **_this bug does not just affect hunters_**. 

1. I was trying to take down a tough rare elite with a poorly geared feral druid, ended up rooting it and kiting a bit while doing some heals.

2. Another mob was hitting me too.

3. After I healed up, I went back to cat form to kill the stray mob, the original roots broke on the elite mob, and at the same time I was spamming mangle on the stray.

4. At that very moment I noticed the cat form was no longer auto-swinging on the stray mob.

As expected, only a full relog brought back autoswings. No feral form shifts or humanoid form were able to bring back the melee swings before doing this.

I suspect this may be a fundamental mob combat / auto swing issue that either affects all classes, or all classes that can have different "auto attack" modes, such as hunters shooting or swinging, or druids who's different forms have different auto-swing properties. It would be wise to figure out which of these is the case.

**Comment by Rushor** [comment]
The issue is fixed once https://github.com/TrinityCore/TrinityCore/commit/587786ce6661fb4741ff623458b3c6c590f642fe was merged to the live realm.

**Comment by TeridanDW** [comment]
Hello after a fast test on PTR this:

> It is possible for Raptor Strike (ID: 2973) (or any other spell which has "on next melee attack") to cause a situation in which the hunter is no longer able to perform any melee attacks whatsoever.

is still happening and gets an error (see below), however it is nolonder needed to relog to fix it, just retarget the creature.
The error that the player gets is:
![wowscrnshot_102117_115259](https://user-images.githubusercontent.com/6797611/31850216-2c813b8e-b657-11e7-97df-387cb272ef7c.jpg)

Up to the developers to decide what to do here.
For me it's a big improvement so changing label.

**Comment by Max0r847** [comment]
Still permanently disabling melee auto-swings on Algalon with hunter. Not applied yet?
