### ISSUE TITLE
[Warlock] Health Funnel - spell power coefficient missing

### ISSUE THREAD

**Issue by Evr1** [dalaranwow/dalaran-wow#239]
The spell health funnel takes away too much hp. The damage amount shown on the screen isn't reliable either. Just look at your hp bar dropping down, it doesn't add up to the damage number on the screen. Basically it keeps ticking the initial cost+the sustained cost instead of the one time initial.

**Comment by Gwylin** [comment]
Is anything happening with this bug? Is there a fix coming? My lock still have this problem and it is making it impossible to play.

**Comment by Rushor** [comment]
cf9fb42f0bd8e035d61b44a49ce90ffb2aab026b
- rank 9 should now remove 520 health each second (no longer doubleticks)
- note the dot_bonus is increased with * 0.558 spellpower from the warlock as can be seen here http://www.wowwiki.com/Health_Funnel?oldid=2184422

**Comment by Golganeth** [comment]
When scaling with spell power, it might be healing a bit too much on PTR. Proof needed
The spell can't kill the caster

**Comment by Jezzybane** [comment]
Its still not working correctly at all.

At level 16 human warlock i got 288 HP (naked) using level 1 Health funnel should take of initial 11 HP plus 5 HP per sec (again without any spellpower) so roughly 61 HP.

If i channel the whole 10 sec i end up at exactly 127 HP so it take around 161. Exactly 100 HP too much.

**Comment by Rushor** [comment]
you know that the stuff scales with spell power?

**Comment by Jezzybane** [comment]
I do know that - but as i said - Level 16 (naked no equipment 0 spellpower) and without any spend Talentpoints i get these results.

**Comment by Rushor** [comment]
oh rigth sry http://wowwiki.wikia.com/wiki/Health_Funnel?oldid=2184422

it should be 54.8% per tick

> Health Funnel allows the Warlock to transfer his own health to his pet. It has a spell power coefficient of 54.8% per tick (548% total). Spell power affects the healing, but does not affect the health cost.

**Comment by Rushor** [comment]
nvm i already have added a spell power coefficient of 54.8% per tick to all ranks of the spell on PTR. So i will reduce it to 51.8 %.

**Comment by Rushor** [comment]
DB/Spell: Health Funnel - Reduce spell power coefficient to 51.8 percent

* updates: https://github.com/dalaranwow/dalaran-wow/issues/239
* commit: 2e936909bcef9a635b96f01a751a30175c9aea39

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello after few tests on PTR the results are:

This:

> The spell health funnel takes away too much hp. The damage amount shown on the screen isn't reliable either. Just look at your hp bar dropping down, it doesn't add up to the damage number on the screen. 

is still an issue.

Investigation of this issue:
 - Even though the combat log says:

> Pure's Health Funnel hits Pure for 182 Shadow.
Jakloz gains 0 Health from Pure's Health Funnel.(520 Overhealed)

at rank 9 the **health lost** should be 182 but it is 520 instead.
The initial cost of the spell should be -->  277 + 182 = 459 , however we have --> 277 + 520 = 797

These results are from new character lvl 80 with 0 spell power.

 - This:

> DB/Spell: Health Funnel - Reduce spell power coefficient to 51.8 percent

works as intended on PTR, however I would like to ask @Rushor why did the coefficient was changed from 54.8% per tick to 51.8% per tick, when wowwiki says 54.8%?

![wowscrnshot_102117_104418](https://user-images.githubusercontent.com/6797611/31849595-5e3aeb2a-b64d-11e7-806f-4ac035ea0211.jpg)

Reopening as the initial issue is still present.
