### ISSUE TITLE
Ring of Law (progression in BRD) / High Justice Grimstone

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2444]
quote from wowhead: High Justice Grimstone can be found within the Ring of Law in Blackrock Depths. He can be targeted, but is not a hostile enemy. Approaching the center of the ring will start an event, and the High Justice will appear and approach one of the gates and let loose a wave of random enemies. Once these have been defeated, he will go to another gate and release a random boss monster. The boss you encounter is not related to the previous enemies in any way; they are both completely random spawns.
This NPC can be found in Blackrock Depths. 

How this encounter executes on algalon: after entering the arena and approaching the middle the door closes and the event starts, the HIgh Justice appears. But instead of High Justice Grimstone announcing the next fight and opening some doors he begins to attack the members of the group (while still untargetable with attacks and spells). No doors opens, no wave of random enemy spawns, it is not possible to venture deeper into blackrock.
high justice grimstone: http://wotlk.openwow.com/npc=10096

**Comment by Shadesmar** [comment]
actually i just found out there is still a way deep down there... using the secret entrance to molten core and then going back.... maybe i try to get the key this way to avoid the ring of law

**Comment by Nikvet** [comment]
When the event begins,he begins to yell,but he also begins to attack the group.We cannot attack him,he's not attackable.Confirmed.

**Comment by Khronos-** [comment]
Confirmed: High Justice Grimstone attacks people and does not trigger the event. Even avoiding agro range seems to be undoable.

Changing this NPC status from Hostile to Neutral to both factions did the work in other realms.

**Comment by koubx** [comment]
Confirmed, the NPC should be hostile (name in red) but non aggressive and non attackable.

There is still a way to do the event: all people stay at close to the entrance, away from that NPC, and don't body pull him. When mobs are sumoned, someone pull them to the group. All have to go back to the entrance before killing the last mob, before the NPC repop to sumon the boss.

If it still fails (because of someone in the group), ask a rogue to picklock, an eng to blast, a BS to use a generic key, or find someone with the shadowforge key to open for you.

**Comment by Bzmode** [comment]
this is still bugged as it is on every trinity core server

**Comment by Khronos-** [comment]
@koubx True, NPC should be hostile. What I suggest is a simple change to workaround while the issue is not permanently fixed.

I've experienced both High Justice Grimstone and the Arena Spectators being Neutral (name in yellow)  in other realms. Seems to have made the event non buggy.

**Comment by nyrpha** [comment]
Just tried doing the Arena event. The Justicar will call two worm adds from the boss tunnel, but no boss appears after they die and then the Justicar starts attacking the group himself, but since he is invulnerable the only way out is to die. Still seems like some polish is needed here.

**Comment by Lothloryen** [comment]
Hello there,

This issue should be solved already, could anyone confirm it, please?

Thank you.

**Comment by Hazarx** [comment]
Its still bugged. I can confirm

**Comment by Golganeth** [comment]
Still an issue, NPC shouldn't attack the players nor should be attackable. Merge with #3155
