### ISSUE TITLE
[Item][Event] Corrupted Ashbringer in Scarlet Monastery

### ISSUE THREAD

**Issue by Loutmourne** [dalaranwow/dalaran-wow#2517]
So, recently I was thinking about supporting server a bit and decided to donate some money. Browsing through shop I bought Corrupted Ashbringer [Item ID:22691].
Equipping it I found some really interesting and weird things that obviously shouldn't be happening. First of all, event in Scarlet Monastery doesn't work. At all. Scarlets remain hostlie, even after unequipping sword and equipping it back.
![wowscrnshot_061215_182637](https://cloud.githubusercontent.com/assets/12653828/8133545/a9b10a62-1131-11e5-95b0-882633375ce7.jpg)
Second thing: all of sudden Alliance NPCs in Dalaran started to aggro at me and became killable.
![wowscrnshot_061215_182942](https://cloud.githubusercontent.com/assets/12653828/8133559/c073bdee-1131-11e5-8a51-18a016be8c27.jpg)
![wowscrnshot_061215_182952](https://cloud.githubusercontent.com/assets/12653828/8133560/c0773b22-1131-11e5-9545-3cce9986aa90.jpg)
Third, I couldn't use flightmaster at Acherus because all of sudden it started spawning Wyverns and Griffons, as if I was attacking it, even though NPC remained friendly to me.
I am yet to test many other things, but this is all I found in first 25 minutes. I'd like to know if this is a known issue and if it is planned to be fixed. In case I find something else, I will post it here.

---

Apparently Ashbringer forces even neutral and low level NPCs to aggro at its wielder and affects bosses at Argent Tournament grounds.
![wowscrnshot_061415_183313](https://cloud.githubusercontent.com/assets/12653828/8164695/59c146fc-1393-11e5-926d-07ec34868e1b.jpg)
Here is the screenshot of another bug I mentioned before, seems like sword affects only neutral flightmasters:
![wowscrnshot_061315_133711](https://cloud.githubusercontent.com/assets/12653828/8164718/87a2797e-1393-11e5-9bb0-775eab740181.jpg)
Third thing I managed to check - debuff "Ashbringer" vanishes after death, which shouldn't really happen as I remember.

Possible problem might be in those two spells: [ID:28282] and [ID:28442]
http://www.wowhead.com/spell=28282/ashbringer
http://www.wowhead.com/spell=28442/ab-effect-001

**Comment by Rushor** [comment]
Summary:
1.) remove factionchange and agressive behaviour from some the aura
2.) Implement ashbringerevent

**Comment by Rushor** [comment]
fix will be pushed tomorrow

**Comment by Rushor** [comment]
Scripts/Scarlet Monastery : Implement Corrupted Ashbringer Event in Scarlet Monastery

* closes https://github.com/dalaranwow/dalaran-wow/issues/2517
* commit: d6aa154b51032fa121fc8e804ff7b4f64f0c4014

![GitHub Logo](http://i.imgur.com/zDXN8gk.jpg)
![GitHub Logo](http://i.imgur.com/tfwLKiD.jpg)
![GitHub Logo](http://i.imgur.com/mq3uraJ.jpg)
![GitHub Logo](http://i.imgur.com/zxNdPzr.jpg)
![GitHub Logo](http://i.imgur.com/xVF99Pr.jpg)
![GitHub Logo](http://i.imgur.com/AjAHZwb.jpg)
![GitHub Logo](http://i.imgur.com/5fMFTq0.jpg)
![GitHub Logo](http://i.imgur.com/wcczvKm.jpg)
![GitHub Logo](http://i.imgur.com/D1Dx3md.jpg)
![GitHub Logo](http://i.imgur.com/AhryPv6.jpg)

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by maladebond** [comment]
Hi Rushor,
i'm actualy running a 1.12.1 serveur and the ashbringer event is not running as it should (same issues than in this post). Would it be possible to get some informations about how to fix it? I would be very grateful.
Thanks by advance.

**Comment by Rushor** [comment]
I fixed the event for a TrinityCore based server (3.3.5). Basically you need to add a script for all creature in the instance that react (kneel + say text + turn friendly) if a player with the ashbringeraura moves close t them. This can be done with ScriptedAI or creatureaiscripts

**Comment by maladebond** [comment]
Thanks for your tips ! I hope that the solutions that worked on your 3.3.5 will work with mine !

**Comment by Bjeffwoff** [comment]
This is not fixed anymore sadly. Donated for the sole purpose of filming this event so was kinda dissapointed that it's still bugged.. The mobs just stand around looking dumb

**Comment by TeridanDW** [comment]
Hello after a quick test on PTR:
 - Small issue with faction:
![image](https://user-images.githubusercontent.com/6797611/32624403-e192c512-c591-11e7-9e01-b7fea7257ed2.png)
 - None of the creatures during the dungeons ever said or used emote at me, so this part is not working

Note: End event works properly.

**Comment by Crispybuilt** [comment]
- Guards are not saying anything/kneeling down before you when you pass next to them.

Can confirm the above issue, however I have to add the following:

- Renault missing 1 crucial starting quote when you enter the Cathedral (should yell that when you open the door and step in)
*Scarlet Commander Mograine yells: Bow down! Kneel before the Ashbringer! A new dawn approaches, brothers and sisters! Our message will be delivered to the filth of this world through the chosen one!*

- Can't talk to Inquisitior Fairbanks at all because he remains "dead"
