### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by cover25** [dalaranwow/dalaran-wow#2521]
Event does not start when you turn into a box. Also you sometimes become an imp. 

Odd.

**Comment by Lothloryen** [comment]
Thank you Cover25,

This quest was working before, but I shall take a look. It will be corrected during one of the next scheduled maintenances.

**Comment by Lothloryen** [comment]
Hello again,

It has been corrected already, after the next maintenance or realm restart it will be working.

Thank you for your report.

**Comment by Zibathy** [comment]
Still not working on Algalon or broke again.

![wowscrnshot_111616_235845](https://cloud.githubusercontent.com/assets/7729864/20378013/09894d50-ac59-11e6-8035-8db7ae18dca9.jpg)
![wowscrnshot_111716_000004](https://cloud.githubusercontent.com/assets/7729864/20378012/0988c3b2-ac59-11e6-8207-abe1173890c3.jpg)
![wowscrnshot_111716_000057](https://cloud.githubusercontent.com/assets/7729864/20378014/0989983c-ac59-11e6-9974-fb92d3127963.jpg)
![wowscrnshot_111716_000101](https://cloud.githubusercontent.com/assets/7729864/20378015/098987de-ac59-11e6-8baf-f7070736bc5c.jpg)

**Comment by Rushor** [comment]
DB/Quest: To Legion Hold - Always summon Deathbringer Jovaan

* closes https://github.com/dalaranwow/dalaran-wow/issues/2521
* commit: a8eb38ddc75e24f7574a27c7dd2f833e10dbd8df

![GitHub Logo](http://i.imgur.com/eeXRPnf.jpg)
![GitHub Logo](http://i.imgur.com/7fzt92q.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr, there is just 1 small detail than needs to be corrected, the purple inferno model should disapear on event start and reapear on event end.
