### ISSUE TITLE
Ulduar - Iron Council

### ISSUE THREAD

**Issue by Althaloss** [dalaranwow/dalaran-wow#2539]
The Runes of Death are instantly killing anyone who is in it's area when it drops. I remember them doing quite a bit of damage every half second, but not one-shotting.

**Comment by warcraftgeekygamer** [comment]
(This information is for the dev's)

Spell: http://www.wowhead.com/spell=62269/rune-of-death
NPC: http://www.wowhead.com/npc=32927/runemaster-molgeim


Rune of Death
Unlimited range
Instant
Requires level 83
Summons a Rune of Death at a random enemy target's location. This rune deals 2750 Shadow damage every half-second to anyone within 13 yards of that location.

**Comment by Lothloryen** [comment]
Hello,

Thank you for your report, this is a very weird issue since it was working perfectly. Let me take a look, please.

**Comment by Vaxsysl** [comment]
Update for Iron Council. I was in a pug that pulled 2 bosses instead of 3, so that may be what triggered such behavior. During HM attempts, he was sometimes spamming Chain Lightning, or casting Overload after Overload, after Overload, and he did not cast his whirlwind ability even once. During normal attempt, it was all the same, but he never flew up either.

Before, he was casting Chain Lightning three times and then whirlwind. Overload was used on random-ish 30-50sec cooldown window or near enough. It may be that 2 boss pull triggered such behavior as I've stated. This was on 10man only. I couldn't join my guilds' Sunday raid evening for few weeks or any 10man run for even longer, so I can't give any observation if it was triggered or is he in this bugged state by default.

**Comment by Lothloryen** [comment]
Hello there,

Every issue listed here should be solved already, it will be applied on the live server after the next scheduled maintenance.

Thank you.

**Comment by seancmurphy** [comment]
Hi this issue is still happening. We were getting hit for 8-10k+. Impossible to run out of.
