### ISSUE TITLE
Priest: [spell][Mind Flay/Pennance] ticks 2 times instead of 3.

### ISSUE THREAD

**Issue by GhostAlgalon** [dalaranwow/dalaran-wow#2606]
Issue: Affected spells only tick twice from channeling them instead of three times since the latest update issued 6th of July. 

The cast ends at 0.3 seconds remaining of the channeling spells for some reason! This was tested with my own haste values, whereas Mind Flay had a base channel cast time of 2.59 seconds and Penance 1.63 seconds, yet both ended at 0.3 seconds remaining - thus leaving out the remaining tick. However the first two ticks do hit at the corresponding times which are 2/3 and 1/3 of the channeling time.

Spells affected: 

Mind Flay [48156]
Pennance [53007]

http://i1.minus.com/iH1KfbV2UlWTt.jpg
http://i2.minus.com/i6GTgez6RaE8F.jpg

How it should work: The channeling spell should be able to run the whole duration, thus ending the remaining tick at 0 seconds left of the channel. 

Edit: I'm receiving reports from multiple sources that channeling spells amongst other classes are not functioning. 

Edit 2: I've tried more channeled spells such as Mind Sear, Hymn of Hope and Divine Hymn. All spells experience the same issue.

**Comment by Vaxsysl** [comment]
It's not just that - all channeling abilities have their last tick removed. Evocation, Arcane Missiles, Blizzard; Penance, Mind Flay, Divine Hymn, Hymn of Hope; Hellfire, Rain of Fire...

Only Bandages seem to be unaffected. Haven't tested Cannibalize or any other class' channeling.

**Comment by n-ghost** [comment]
Checked Arcane Missiles rank 6 and Evocation, they're doing 5 and 4 ticks respectively.

**Comment by n-ghost** [comment]
People are reporting that the haste rating is to blame. 

Also, my own test was on lowbie mage with 0 haste.

**Comment by defias** [comment]
Arcane missiles are bugged. Tick 4 times instead of 5 times. Source: lvl 80 arcane mage main.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for reporting this. Already working on it.

**Comment by Lothloryen** [comment]
Hello again,

This issue has been fixed, it will be on the live server after the next scheduled maintenance.

Thank you very much.

**Comment by Edzero** [comment]
This still occurs on the live realm, can a staff member confirm whether the fix was applied to the live realm? 

Either it is currently not applied or the fix doesn't work as intended. 

Thank you.

**Comment by Rushor** [comment]
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/2983
