### ISSUE TITLE
[Quest] Spells/Auras: [Realm of Shadows] hides Archerus teleports

### ISSUE THREAD

**Issue by Anecho** [dalaranwow/dalaran-wow#2693]
[[Realm of shadows]](http://wotlk.openwow.com/spell=52275) aura which is applied by [[Salanar the Horseman]](http://wotlk.openwow.com/npc=28653) from [[Into the Realm of Shadows]](http://wotlk.openwow.com/quest=12687) quest makes invisible all objects and NPCs within Archerus, making it impossible to leave it.
![ss](http://failiem.lv/down.php?i=beigkip)

> _(Gotto archerus by using un-stuck ability btw)_

**Comment by Rushor** [comment]
this was fixed with

https://github.com/TrinityCore/TrinityCore/commit/359df54b79fcfa9d95ddd9d2d891f6e26697e476

already on ptr

**Comment by TeridanDW** [comment]
This is still an issue on ptr, if you take the quest > click on the gossip menu > you get the aura 52275> you teleport to acherus (by hearthstone or unstuck option) > player gets stucked inside.
Possible solution: add area check for spell http://wotlk.openwow.com/spell=52275 so if you leave the selected the areas you will lose the aura.
