### ISSUE TITLE
Ulduar: Algalon (Boss) Issues since last Update

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#2751]
Greetings, I'll adress some issues with 10 & 25 Algalon which are currently happening.

**For 10 & 25** - When you attempt Algalon the first time (first pull after spawn), he will randomly activate during his roleplay, with us not being able to target him, and he will kill 5-6 people before he actually turns to be attackable. On the 2nd, 3rd and so on pull, everything seems to work normally. He stands still and he waits for his roleplay to pass and then he becomes attackable.

**25 Issues - Cosmic Smash** - When he casts cosmic smash, you can see visible red fissure (void zone) spawns down on the ground, after that you can see "Yellow Triggers" falling from the sky and when they hit the ground, there is going to be a 2 second delay on explosion. After that triggers will fly up to the sky and simply vanish. The biggest issue here is that the actual explosion which is not synced with the animation and visible triggers must be removed so they do not interfere with the players.

_Cosmic Smash_ on 10 man though works perfectly just like on retail, the 25 has to be corrected.

That is about it, hope it gets fixed soon. Cheers

**Comment by Alver1** [comment]
Confirmed.

**Comment by Crispybuilt** [comment]
![10man](https://cloud.githubusercontent.com/assets/5054924/9023072/7b5d130e-3841-11e5-8202-81a673bb5c08.png)
Today, something weird happened on 10 man, we clicked on the device to spawn Algalon and when we entered there was one already spawned for some reason. As soon as the Brann entered, the 2nd one spawned as well.

This should be fixed as well asap.

**Comment by Tarpor** [comment]
wow I bet you spawned 2 on purpose. NoKappa

**Comment by Alver1** [comment]
Don't worry Tarpor, we learnt from your mistakes.

**Comment by fsironman** [comment]
Making the Cosmic Smash trigger really a trigger:
`UPDATE world.creature_template SET flags_extra='128' WHERE entry='34131';`

Cosmic Smash fix:
boss_algalon_the_observer.cpp:
`case NPC_ALGALON_STALKER_ASTEROID_TARGET_02:`
`summon->m_Events.AddEvent(new CosmicSmashDamageEvent(summon),`
`summon->m_Events.CalculateTime(700));`

down from 3250

**Comment by Lothloryen** [comment]
Hello there,

This encounter was working quite well, but for some reason those issues appeared. They were corrected already and shall be deployed to the live server.

Thank you.

**Comment by Crispybuilt** [comment]
**Cosmic Smash Issue 25man mode:**
- This issue is still present on Live and from the recent test on PTR it is there as well.
----------

**Issue 1:** Visible trigger falling from Sky and hitting the ground 
- 33105 - [Algalon Stalker Asteroid Target 02] -
**Issue 2:** After explosion, trigger flies up to the air from whence it spawned - 
**Issue 3:** Delay on Cosmic Smash explosion and ground hitting.

If fix from 10 can be applied to 25, it would work just fine.

---------------------

For Comparison between 10 & 25 Mode:

10 Man mode (Working fine)
![giphy](https://user-images.githubusercontent.com/5054924/31686436-6a8cc19c-b386-11e7-9d28-5016fb92b0ea.gif)

25 Man mode (Not working correctly)
![giphy123](https://user-images.githubusercontent.com/5054924/31686441-6c9629c4-b386-11e7-94d1-774e762318fc.gif)

**Comment by Lothloryen** [comment]
On PTR.

**Comment by TeridanDW** [comment]
Hello after few tests on PTR the results are:
 - Issue 1:

> For 10 & 25 - When you attempt Algalon the first time (first pull after spawn), he will randomly activate during his roleplay, with us not being able to target him, and he will kill 5-6 people before he actually turns to be attackable. On the 2nd, 3rd and so on pull, everything seems to work normally. He stands still and he waits for his roleplay to pass and then he becomes attackable.

Couldn't reproduce it anymore (fixed).

 - Issue 2:

> Cosmic Smash Issue 25man mode:

> Issue 1: Visible trigger falling from Sky and hitting the ground.

Is fixed, trigger is nolonger visible to players.

> Issue 2: After explosion, trigger flies up to the air from whence it spawned.

Players can't see the trigger anymore.

> Issue 3: Delay on Cosmic Smash explosion and ground hitting.

This is still an issue.

Proof:
From 10m version of the encounter - the timing and visuals are perfect:
https://www.youtube.com/watch?v=GwMPfTNTU64&feature=youtu.be

From 25m version of the encounter - the timing and visuals are desyncronizied:
https://www.youtube.com/watch?v=353Xz6CoCSk&feature=youtu.be

**Comment by Crispybuilt** [comment]
@Teridan Is 25m Cosmic Smash delay/sync still not fixed properly?

**Comment by TeridanDW** [comment]
Yes, the 25m issues still stand.

**Comment by Crispybuilt** [comment]
@Lothloryen Reminder
