### ISSUE TITLE
Quest: On Ruby Wings

### ISSUE THREAD

**Issue by JackMV** [dalaranwow/dalaran-wow#2843]
For this quest you are supposed to use your red dragon to kill [Thiassi the Lightning Bringer] (http://www.wowhead.com/npc=28018/thiassi-the-lightning-bringer) who has [Grand Necrolord Antiok](http://www.wowhead.com/npc=28006/grand-necrolord-antiok) riding on his shoulder. The way the quest is intended to work, Antiok is supposed to be immune to damage until Thiassi is killed at which point you are supposed to get off of your dragon and kill him, however when I killed Thiassi using my dragon, Antiok would disappear. I was able to complete the quest by killing Antiok using ranged attacks which should not be doable since he has a buff that makes him immune to damage. This worked against my first attack, however he lost that buff after entering combat with me.

**Comment by Sagrath** [comment]
Confirmed

**Comment by Sagrath** [comment]
The quest item Ruby Beacon of the Dragon Queen (#38302) cannot be used in the Wicked Coil.
 
The item says it can be used in the Wicked Coil, but it cannot. It needs to be usable in the Wicked Coil.

Killing Thiassi the Lightning Bringer does nothing. Grand Necrolord Antiok is often times nowhere on Thiassi the Lightning Bringer. This killing him does not knock you off the dragon, and you cannot kill Antiok because he isn't there.

When Grand Necrolord Antiok is ACTUALLY THERE, he knocks you off the dragon immediately, just to be slain...

What should actually happen is you should kill Thiassi, and THEN he knocks you off, and THEN you kill Necrolord.

Dismounting the Wyrmrest Vanquisher causes you to take melee attacks from the Wyrmrest Vanquisher who appears to be invisible. I'm thinking that he becomes hostile (and invisible) after you dismount him....

 He should just fly away when you dismount. No killing necessary....

Entering Combat with a mob causes the Wyrmrest Vanquisher to immediately plummet toward the ground or suddenly teleport on the ground.

 Entering combat should have no effect on the position or direction of the Wyrmrest Vanquisher.

**Comment by NovaHiros** [comment]
All of the above is still there - quests involving vehicles are 100% bugged and should be auto-complete, imho.

**Comment by rinleezwins** [comment]
Completed the quest by just dismounting the dragon and killing Antiok. If you position yourself, you can actually melee hiim so it wasn't very difficult.

**Comment by jonanone** [comment]
Antiok is now immune to damage when on top of Thiassi. Once Thiassi is defeated, Antiok will drop the player from the drake and its immune shield will be gone. The update will be applied to the live realm soon.

**Comment by Golganeth** [comment]
The first time, Antiok was on solid ground and disappeared as soon as Thiassi was pulled. After Thiassi died, nothing happened.

After Thiassi respawned, Antiok was properly mounted on it. After I killed Thiassi again, I had to manually dismount and then kill Antiok. The immune shield from Antiok disappears as soon as Thiassi is pulled, but he doesn't take damage from the drake anyway.

Needs polishments.

**Comment by Lothloryen** [comment]
This was fixed on Algalon, thank you.

**Comment by Xandriarn** [comment]
The above comment about the Wyrmrest Vanquisher still happens:

"Dismounting the Wyrmrest Vanquisher causes you to take melee attacks from the Wyrmrest Vanquisher who appears to be invisible. I'm thinking that he becomes hostile (and invisible) after you dismount him....

He should just fly away when you dismount. No killing necessary....

Entering Combat with a mob causes the Wyrmrest Vanquisher to immediately plummet toward the ground or suddenly teleport on the ground.

Entering combat should have no effect on the position or direction of the Wyrmrest Vanquisher."

The flying into the ground bug happened and also when I attempted to dismount to fight Antiok after killing Thiassi I was melee'd to death before I could engage Antiok. I saw an undead warlock that this appeared to happed to as I was running back to my corpse as well. Fortunately Antiok was still dismounted and I could kill him to complete the quest. I then summoned the Wyrmrest Vanquisher again to fly me back to the temple (which did not work on the Wicked Coil as the tooltip says). Upon dismounting at the top of the temple I was melee'd to death again. See screenshot.

![image](https://cloud.githubusercontent.com/assets/25491266/24165753/469b85da-0e3f-11e7-8ae2-2d1ae3663852.png)
