### ISSUE TITLE
[Warlock] Chaos bolt - Missing ignore resistance

### ISSUE THREAD

**Issue by moonsado** [dalaranwow/dalaran-wow#3014]
Hello,
At the time I am writing this chaos bolt randomly does not pierce threw shields like priest's shield , mana shield. It sometimes goes threw, sometimes it doesn't, leaving it to chance. 
Normally it should go thew every type of shield except for divine shield.
I quote from http://wotlk.openwow.com/spell=59172  "Chaos Bolt cannot be resisted, and pierces through all absorption effects."
It doesn't say 50/50 chance.

**Comment by ConradSilverwind** [comment]
You missed one here, chaos bolt should penetrate divine shield and other invulnerability effects since it's wotlk. The only way to resist chaos bolt is to stack resilience or reflect it.

Cheers.

**Comment by Rushor** [comment]
Game/Unit: CalcSpellResistance - Chaos Bolt should not be resisted

* closes https://github.com/dalaranwow/dalaran-wow/issues/3014
* commit: 25ffe6233919de817dd6cd9d8e7058be711c057e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

This:

> You missed one here, chaos bolt should penetrate divine shield and other invulnerability effects since it's wotlk.

is not true (in my mind), feel free to prove me wrong by provinding a video from retail (wrath) that shows Chaos Bolt going though Divine Shield. Untill then I find this statement as invalid.

**Comment by Skipslegdays** [comment]
I believe this is not fully fixed. Chaos Bolt deals reduced damage against Dispersion. This was an issue when I played here in 2016 and is still happening now.
