### ISSUE TITLE
[Hunter] Traps

### ISSUE THREAD

**Issue by Winstrol** [dalaranwow/dalaran-wow#3026]
Currently enemy's can see hunter traps, while only friend targets should be able to.

github.com/TrinityCore/TrinityCore/issues/10376

heres another issue with traps and stealth (tested and confirmed with my rogue)

github.com/TrinityCore/TrinityCore/issues/10179

**Comment by Winstrol** [comment]
https://github.com/TrinityCore/TrinityCore/issues/10376

**Comment by Winstrol** [comment]
noticed traps activation radius is way too low on this server, people run straight trough my traps, even when running behind me
github.com/TrinityCore/TrinityCore/issues/503

**Comment by Celfinnel** [comment]
Aside from the radius, sometimes mob walks straight through the trap and trap does not activate at all

**Comment by robinsch** [comment]
@Winstrol: Can you find some 3.3.x Hunter Videos where we can see the Trap range?

**Comment by KazJR** [comment]
https://www.youtube.com/watch?v=G_m9hwU75No at about 2minutes in, you see him placing a frost trap, wich the warrior then activates (at what I belive is a bigger range than what we currently have)

**Comment by KerDW** [comment]
Any update on this? @KazJR provided proof enough. The fact that a target with high resilience in arena can just run away from scatter -> trap should be proof enough anyway.

**Comment by Rushor** [comment]
ping @robinsch :)

**Comment by robinsch** [comment]
ping @Lothloryen :) working fine on PTR.

Ref: https://github.com/TrinityCore/TrinityCore/pull/4726/files

**Comment by KerDW** [comment]
If this is of any help, I tested on Algalon and the radius seems to be less than 5 yards, what it should be. The only radius change in retail has been in 2015, a change from 5y to 3y.   http://wow.gamepedia.com/Freezing_Trap

**Comment by robinsch** [comment]
Oh my bad I totally missread the issue. I will check trap activation range.

@KerDW Does the stealth issue still exists?

**Comment by robinsch** [comment]
Here are current trap values, note this is diameter
```
+-----------------------------------------------+-------+
| name                                          | data2 |
+-----------------------------------------------+-------+
| Musty Tome Trap                               |     0 |
| Freezing Trap                                 |     5 |
| Deepmoss Eggs trap                            |     0 |
| Venture Co. Wagon Trap                        |     0 |
| Witherbark Totem Bundle TRAP                  |     0 |
| Night Elven Bear Trap                         |     0 |
| Rat Bomb Trap                                 |     0 |
| Magenta Cap Clusters Trap                     |     0 |
| Gordunni Trap                                 |     0 |
| Immolation Trap                               |     5 |
| Frost Trap                                    |     5 |
| Explosive Trap                                |     5 |
| Immolation Trap II                            |     5 |
| Immolation Trap III                           |     5 |
| Immolation Trap IV                            |     5 |
| Immolation Trap V                             |     5 |
| Freezing Trap II                              |     5 |
| Freezing Trap III                             |     5 |
| Explosive Trap II                             |     5 |
| Explosive Trap III                            |     5 |
| Dark Iron Ale TRAP                            |     0 |
| Keg Trap                                      |     0 |
| Challenge to Urok Trap                        |     0 |
| Finkle Trap                                   |    50 |
| Horgus' Skull Trap                            |     0 |
| Sword of Marduk Trap                          |     0 |
| Haunted Trap                                  |     0 |
| Strange Lockbox Agility Trap                  |     0 |
| Doodad_OnyziasLairLavaTrap51                  |     0 |
| Doodad_OnyziasLairLavaTrapMirror20            |     0 |
| Doodad_OnyziasLairLavaTrapMirror21            |     0 |
| Doodad_OnyziasLairLavaTrap52                  |     0 |
| Doodad_OnyziasLairLavaTrap53                  |     0 |
| Doodad_OnyziasLairLavaTrap54                  |     0 |
| Doodad_OnyziasLairLavaTrap55                  |     0 |
| Doodad_OnyziasLairLavaTrap56                  |     0 |
| Doodad_OnyziasLairLavaTrap57                  |     0 |
| Doodad_OnyziasLairLavaTrap58                  |     0 |
| Doodad_OnyziasLairLavaTrap59                  |     0 |
| Doodad_OnyziasLairLavaTrap60                  |     0 |
| Doodad_OnyziasLairLavaTrap61                  |     0 |
| Doodad_OnyziasLairLavaTrap62                  |     0 |
| Doodad_OnyziasLairLavaTrap63                  |     0 |
| Doodad_OnyziasLairLavaTrap64                  |     0 |
| Doodad_OnyziasLairLavaTrap65                  |     0 |
| Doodad_OnyziasLairLavaTrap66                  |     0 |
| Doodad_OnyziasLairLavaTrap67                  |     0 |
| Doodad_OnyziasLairLavaTrap68                  |     0 |
| Doodad_OnyziasLairLavaTrapMirror22            |     0 |
| Doodad_OnyziasLairLavaTrap69                  |     0 |
| Doodad_OnyziasLairLavaTrap70                  |     0 |
| Doodad_OnyziasLairLavaTrap71                  |     0 |
| Doodad_OnyziasLairLavaTrap72                  |     0 |
| Doodad_OnyziasLairLavaTrapMirror23            |     0 |
| Doodad_OnyziasLairLavaTrapMirror24            |     0 |
| Doodad_OnyziasLairLavaTrapMirror25            |     0 |
| Doodad_OnyziasLairLavaTrapMirror26            |     0 |
| Doodad_OnyziasLairLavaTrapMirror27            |     0 |
| Doodad_OnyziasLairLavaTrapMirror28            |     0 |
| Doodad_OnyziasLairLavaTrapMirror29            |     0 |
| Doodad_OnyziasLairLavaTrapMirror30            |     0 |
| Doodad_OnyziasLairLavaTrapMirror31            |     0 |
| Doodad_OnyziasLairLavaTrapMirror32            |     0 |
| Doodad_OnyziasLairLavaTrapMirror33            |     0 |
| Doodad_OnyziasLairLavaTrapMirror34            |     0 |
| Doodad_OnyziasLairLavaTrap73                  |     0 |
| Doodad_OnyziasLairLavaTrap74                  |     0 |
| Doodad_OnyziasLairLavaTrap75                  |     0 |
| Doodad_OnyziasLairLavaTrap76                  |     0 |
| Doodad_OnyziasLairLavaTrap77                  |     0 |
| Doodad_OnyziasLairLavaTrap78                  |     0 |
| Doodad_OnyziasLairLavaTrap79                  |     0 |
| Doodad_OnyziasLairLavaTrap80                  |     0 |
| Doodad_OnyziasLairLavaTrap81                  |     0 |
| Doodad_OnyziasLairLavaTrap82                  |     0 |
| Doodad_OnyziasLairLavaTrap83                  |     0 |
| Doodad_OnyziasLairLavaTrapMirror35            |     0 |
| Doodad_OnyziasLairLavaTrapMirror36            |     0 |
| Doodad_OnyziasLairLavaTrapMirror37            |     0 |
| Doodad_OnyziasLairLavaTrapMirror38            |     0 |
| Fixed Trap                                    |     0 |
| Whipweed Entangle Trap                        |     0 |
| Sand Trap                                     |     0 |
| PX-238 Winter Wondervolt TRAP                 |     8 |
| Elune's Blessing TRAP BUFF                    |     8 |
| Immolation Trap VI                            |     5 |
| Explosive Trap IV                             |     5 |
| Ectoplasmic Distiller Trap                    |     0 |
| Midsummer Bonfire Campfire Damage Trap        |     2 |
| Fire Festival Fury Trap                       |     0 |
| Doodad_OnyziasLairLavaTrap80                  |     0 |
| Doodad_OnyziasLairLavaTrap79                  |     0 |
| Doodad_OnyziasLairLavaTrap78                  |     0 |
| Doodad_OnyziasLairLavaTrap64                  |     0 |
| Doodad_OnyziasLairLavaTrap72                  |     0 |
| Doodad_OnyziasLairLavaTrap81                  |     0 |
| Doodad_OnyziasLairLavaTrap82                  |     0 |
| Doodad_OnyziasLairLavaTrap83                  |     0 |
| Tainted Soil Trap                             |     0 |
| Battered Crate Trap                           |     3 |
| Box of Mushrooms Trap                         |     0 |
| Freezing Trap                                 |    15 |
| Aldor Altar Trap                              |     0 |
| Snake Trap                                    |     5 |
| Aura Trap Purple Tall                         |     0 |
| Aura Trap Blue Tall (scale 3.00)              |     0 |
| Aura Trap Yellow Tall (scale 2.00)            |     0 |
| Netherwing Egg Trap (Gas)                     |     0 |
| Apple Trap                                    |    10 |
| Naj'entus Spine Trap                          |     0 |
| Frost Trap                                    |     5 |
| Pamela's Doll's Trap                          |     0 |
| Freezing Trap                                 |     5 |
| Snake Trap                                    |     5 |
| Explosive Trap                                |     5 |
| Conspicuous Crate Green Trap                  |     0 |
| Aura Trap Red Short                           |     0 |
| Firethorn Trap                                |     0 |
| Bear Trap                                     |     5 |
| Whisper Gulch Ore Trap                        |     0 |
| Sprung Trap                                   |     0 |
| Sprung Trap (Despawn Critter)                 |     0 |
| Canopic Trap                                  |     0 |
| Dome, Enter Dome Trap, Alliance               |     0 |
| Dome, Enter Dome Trap, Horde                  |     0 |
| Aura Trap Green Short                         |     0 |
| Freezing Trap                                 |     5 |
| Arcane Trap                                   |     5 |
| Immolation Trap VII                           |     5 |
| Immolation Trap VIII                          |     5 |
| Explosive Trap V                              |     5 |
| Explosive Trap VI                             |     5 |
| Hemet's Immolation Trap                       |     5 |
| Zul'Drak - Zol'Maz Stronghold Cache Trap      |     0 |
| Spike Trap                                    |     5 |
| Freezing Trap                                 |     5 |
| Croc Trap                                     |    15 |
| Spike Trap                                    |     5 |
| Volatile Trap                                 |     5 |
| RX-214 Repair-o-matic Station TRAP            |     8 |
| Cosmetic Explosion Trap                       |     0 |
| Aura Trap Blue Short                          |     0 |
| Infused Saronite Bar Trap                     |     0 |
| Frost Trap                                    |     5 |
| Easter Egg Trap                               |     0 |
| Elune's Blessing TRAP QUESTCREDIT             |     8 |
| Dark Iron Mole Machine (Minion Summoner Trap) |     0 |
| Thor Modan Mole Machine Trap                  |     0 |
| Ensnaring Trap                                |     5 |
+-----------------------------------------------+-------+
149 rows in set
```

**Comment by KerDW** [comment]
The stealth issue is definitely not fixed on Algalon, I have been testing and it just works weird, the trap was appearing and disappearing based on distance, sometimes it didn't disappear at all. This was tested on a duel against an alt of mine in dalaran sewers. The trap range seems fine if that data is correct, maybe it is the arming time that's not accurate? It should be 1s, that can be checked in the link I mentioned above. Thank you for the quick and helpful responses :).

**Comment by KerDW** [comment]
Also while we're at it, traps out of combat should not have an arming time as they do now on Algalon, they just shouldn't work with Feign Death for instant CCs.

**Comment by robinsch** [comment]
They should have a arming timer. It should be 0.5 seconds.

**Comment by KerDW** [comment]
You're right there I guess, I just knew it was a very quick arming time so I assumed there was none. Any update in the combat arming time? Definitely seems bugged on Algalon.

**Comment by Rushor** [comment]
DB/Spell: Corrected arming timer for Freezing Trap

* commit: 6ee521b1ff0ea490bae3142d276364ac10b6369a

by @robinsch 

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

@KerDw Arming Time on ptr in combat is the same like out of combat

```c++
                case GAMEOBJECT_TYPE_TRAP:
                {
                    // Arming Time for GAMEOBJECT_TYPE_TRAP (6)
                    GameObjectTemplate const* goInfo = GetGOInfo();
                    // Bombs
                    if (goInfo->trap.type == 2)
                        // Hardcoded tooltip value
                        m_cooldownTime = time(NULL) + 10;
                    else if (Unit* owner = GetOwner())
                        m_cooldownTime = time(NULL) + goInfo->trap.startDelay;

                    SetLootState(GO_READY);
                    break;
                }
```

**Comment by robinsch** [comment]
@KerDW Arming timer is one second on all traps - there was a freezing trap that had two seconds (but I doub this was a player spell). Sadly without a bigger rewrite we can't implement the 0.5 seconds arming timer because all our timers are seconds (instead of milliseconds).

**Comment by KerDW** [comment]
@Rushor It's working differently than on Algalon then. Also the stealth issue still exists so this isn't completely fixed yet. Is it happening on the PTR?
@robinsch You mean on the PTR I suppose? Because it's not like that on Algalon, video proof of that is here https://www.youtube.com/watch?v=CcIA5Da3mJo. As you can see most of them are definitely taking 2s to arm. But I think only Loth can fix it on Algalon? Well if that's the case he doesn't need to test since he has proof already.

**Comment by Rushor** [comment]
The stealthmechanic is fine on ptr (for me at least) so some previous updates seems to be missing on the liveserver then.

**Comment by Rushor** [comment]
Core/Spell: Trap radius cleanup
commit: 8d594a9ca2224d4a49e0f6c115e6a2ec9b82039e
DB/Spell: Corrected arming timer for Freezing Trap
6ee521b1ff0ea490bae3142d276364ac10b6369a

**Comment by KerDW** [comment]
@Rushor Will the traps' arming time and the stealth bug be also fixed with these corrections when they're implemented on the live server?

**Comment by Rushor** [comment]
once https://github.com/TrinityCore/TrinityCore/pull/4726/files was reviewed and applied yes

**Comment by TeridanDW** [comment]
After some duels on ptr, I think some of the fixes are not applied.
From this report we have few issues:

 - Currently enemy's can see hunter traps, while only friend targets should be able to.

This one is still a problem:
![wowscrnshot_101417_111228](https://user-images.githubusercontent.com/6797611/31574140-0c31e728-b0d2-11e7-8a16-a0251dc84b98.jpg)

 - Hunter trap vs invisibility/stealthed creatures

This one is still a problem:
![wowscrnshot_101417_112520](https://user-images.githubusercontent.com/6797611/31574157-6544e23e-b0d2-11e7-82a0-2bb2ea9df39a.jpg)
and the trap disappeared after a second.

 - Activation range

This seems to be working properly on ptr:
![wowscrnshot_101417_112913](https://user-images.githubusercontent.com/6797611/31574184-f725529c-b0d2-11e7-9b1b-0cb7b2e427a3.jpg)

 - DB/Spell: Corrected arming timer for Freezing Trap (1 sec)

This seems to be working properly on ptr:
![wowscrnshot_101417_113334](https://user-images.githubusercontent.com/6797611/31574218-9ac5a942-b0d3-11e7-8051-5474b3f2738b.jpg)
![wowscrnshot_101417_113335](https://user-images.githubusercontent.com/6797611/31574219-9d578ad6-b0d3-11e7-9729-126c4d9936fa.jpg)

**Comment by KerDW** [comment]
@TeridanDW @robinsch When will the correct arming timer for the traps be pushed to live? It's been wrong for a very long time now there and it really hurts hunters in PvP.

**Comment by Lothloryen** [comment]
@kerDw 
DB/Spell: Corrected arming timer for Freezing Trap (1 sec)
Core/Spell: Trap radius cleanup

Are already deployed to the live server, the issue with the trap visibility still needs to be corrected.

Thank you.

**Comment by KerDW** [comment]
@Lothloryen @TeridanDW @robinsch Thanks for answering Loth, however, I rested all the traps several times and they are still being armed in 2 seconds, including Freezing Trap. 

Besides, tt's not only Freezing Trap which needs an arming timer fix, it's all of them including Freezing Arrow. Snake trap, Immolation Trap, Explosive Trap, Frost Trap, Freezing Trap, Freezing Arrow.

I can provide video proof again if needed.

**Comment by KerDW** [comment]
Another report about traps, Snake Trap.

The snakes from this trap are often very unresponsive and some of them don't attack enemies.

Proof: https://www.youtube.com/watch?v=Mt2KmWDqsT8

**Comment by TeridanDW** [comment]
That:

> they are still being armed in 2 seconds, including Freezing Trap.

is true. I've tested it with timer just once and it seems I was wrong, sorry.

Updating the comment above.

**Comment by robinsch** [comment]
- [ ] Traps Vs. Stealth

- [ ] Trap arming timer

- [ ] Trap visibility

**Comment by robinsch** [comment]
I've tested Freezing Arrow and the arming timer is 1 second.

https://i.gyazo.com/448cd28db2da1cab6820ef99c2ecf725.png

**Comment by KerDW** [comment]
@robinsch you mean on PTR? Because it's 2 seconds on live as of now, just tested it.

**Comment by TeridanDW** [comment]
@KerDW monitor the labels (top right of the report), when you see "Fixed - On Live Server" then you can test it.

**Comment by robinsch** [comment]
Merge https://github.com/TrinityCore/TrinityCore/commit/7567cafec84080d26ea513242a1f540a823b8f9d to fix arming timer.

**Comment by robinsch** [comment]
Okay, I imported the above mentioned commit and also fixed that the arming timer is cut by half if the hunter is out of combat.

**Comment by robinsch** [comment]
Visibility part fixed too. Please create a new issue for Snake Trap.

Waiting for PTR update.

**Comment by TeridanDW** [comment]
Retested everything and the results are:

> Currently enemy's can see hunter traps, while only friend targets should be able to.

fixed.

> Hunter trap vs invisibility/stealthed creatures

fixed.


> Activation range

was already working from before.

> DB/Spell: Corrected arming timer for Freezing Trap (1 sec)

This one is **VERY HARD** to time it. Here is what I can say for sure:
 - Activation time when hunter is out of combat is shorter than when the hunter is in combat.

After ~ 30 tests on each situation the results are:
 - out of combat aim time between 0.5s - 1s
 - in combat aim time ~ 1.5s

Again don't take these values as "fixed" I simple can't time them properly with stopwatch. Think this can go to live and get feedback from there.

Thanks for the assist Tyr.

**Comment by KerDW** [comment]
@TeridanDW Can't you record your own screen with a program like Fraps then use an editor to see exactly how much time it actually takes?

**Comment by TeridanDW** [comment]
Alright, I've recorded few tests, you can try to do the timing, if you want to.

https://www.youtube.com/watch?v=_vVkj0iUlI4&feature=youtu.be

**Comment by KerDW** [comment]
Thanks for sharing the video, the arming time seems to be correct. 

I slowed down the video as much as I could and I timed the trap and the freeze times.

https://www.youtube.com/watch?v=-Vu881fX8UA

The video is 1,8s long, the trap lands at 0,8 seconds, since the arming time starts counting when the trap lands on the ground the trap should be fixed. If out of combat is exactly half of the time this takes it should be fine. 

Thanks for the effort.

**Comment by Lothloryen** [comment]
Hello there,

Everything on live server, feedback would be welcome.

Thank you very much.

**Comment by KerDW** [comment]
@Lothloryen Timer seems fixed, will report with the rest of the stuff later.

**Comment by KerDW** [comment]
@Lothloryen @TeridanDW 

The fixes are fine as far as I've tested, there are new issues that should be hotfixed though.

The only trap that is working on PvE right now is explosive trap, and even then it doesn't give you threat or put you in combat. The rest of the traps are just not working in PvE.

**Comment by Lothloryen** [comment]
> The only trap that is working on PvE right now is explosive trap, and even then it doesn't give you threat or put you in combat. The rest of the traps are just not working in PvE.

Hello @KerDW , this is not working after today's maintenance, right?

**Comment by KerDW** [comment]
@Lothloryen Yes, this started happening after today's maintenance.

**Comment by Lothloryen** [comment]
Hello - yes, just tested it by myself. Reverting the changes related to the arming timer for now.

Thank you.

**Comment by KerDW** [comment]
@Lothloryen Oh well, it's for the best I guess, is there an ETA for the arming timer fix? It's pretty crucial for PvP. Thanks.

**Comment by TeridanDW** [comment]
I would like to add #3698 to this report as they seems to use the same logic as the traps.

**Comment by TeridanDW** [comment]
Few more tests after recent fixes on PTR:
Issue:

>  - The only trap that is working on PvE right now is explosive trap

All traps now work in pve.

>  - and even then it doesn't give you threat or put you in combat. 

All traps now "give" the player threat and correctly put him in combat.

Retest of the original issues:

>  - Currently enemy's can see hunter traps, while only friend targets should be able to.

Fixed.

>  - Hunter trap vs invisibility/stealthed creatures

Traps work properly vs stealthed targets, however vs invisible one they have the old issue of player simple walking over the trap and it( the trap) just disappears without any effect on player.
Additional issue that I saw related to this:
Mage with spell https://wowgaming.altervista.org/aowow/?spell=66 active nolonger see what happens around him, meaning every player/creature disappears for him (while the spell is active).
![image](https://user-images.githubusercontent.com/6797611/31888856-4cf19138-b806-11e7-9f9d-4c70bfc1ba0b.png)
![image](https://user-images.githubusercontent.com/6797611/31888864-5672981a-b806-11e7-96e5-0058d1da4000.png)

>  - Activation range

Fixed.

>  - DB/Spell: Corrected arming timer for Freezing Trap (1 sec)

Fixed.

**Comment by TeridanDW** [comment]
Ignore this:

> Mage with spell https://wowgaming.altervista.org/aowow/?spell=66 active nolonger see what happens around him

That's cata + mechanic, my bad, sorry.

**Comment by KerDW** [comment]
So the only thing left to fix is traps against invisible units, right? Just a bumping since it's a very important fix IMO.

**Comment by robinsch** [comment]
Yes, and I will rank the left over low priority.

**Comment by robinsch** [comment]
We will keep Invisibility bug in a new ticket.

**Comment by KerDW** [comment]
Just as a reminder, Loth reverted the traps' arming timers so that still remains to be applied. @robinsch

**Comment by Lothloryen** [comment]
Yes, it is already scheduled to be re-aplied together with the correspondant fixes with next maintenance.

Thank you.
