### ISSUE TITLE
[QUEST - URGENT] - The Lost Mistwhisper Treasure

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#3176]
I have tried this quest several times and it doesn't seems to be doable.

This however is not an issue about the Wolvars not being target-able. Even though that is also happening right now (and should be eventually fixed), that part can still be overlooked by the fact that, as some have reported, you may kill them with AoE skills or a pet. Therefore this is not the main issue.

The main issue is that even after acquiring the orb, and then killing the Wolvar guy with AoE or/and a pet, the quest will shown as complete but the NPC won't accept it, making it impossible to finish. The bigger issue around this is that this quest is part of the quest chain that allows the player to farm reputation with either the Frenzyheart Tribe or the Oracles. In addition, seems that without the rest of this quest chain, it is impossible to complete the achievement Into the Basin (region loremaster).

This issue is of big importance to me because I have been killing my ass off to get the loremaster achievement, and bugged quests have made it harder (specially on Outlands), but not being able to complete a region's loremaster because of a single bugged quest is massively disappointing.

I hope this becomes fixed soon. It seems like an easy fix but I can't really say because I don't know much. All I want is to be able to complete this quest or at least be able to move along with the quest chain.

Thanks for the attention.

**Comment by Golganeth** [comment]
The issue is already reported here: #344 
Make an in-game ticket and your issue will be sorted out. Closing up

**Comment by Lothloryen** [comment]
This issue should be solved after this next maintenance.

Thank you.

**Comment by DrFuler** [comment]
If it does, it will make me a very happy player!

Thanks!

**Comment by dailyspesh** [comment]
This issue is still ongoing as described; my "Continue" box is greyed out despite having the item and mob kill credit. I have made an in-game ticket as directed.
