### ISSUE TITLE
ToGC -Twin Valkyr stops casting dark/light surges

### ISSUE THREAD

**Issue by hAkonf** [dalaranwow/dalaran-wow#3238]
When you interrupt either of the Twin's Pact, said twin will stop casting the constant ticking (the surges).
This results in the raid taking under half the damage intended, and thus making the encounter waaaay too easy.
So for example if you get 2 shields as your first specials, you literally can't wipe.
Bug has been around for a long time now, and I think it's time it's fixed.

**Comment by Crispybuilt** [comment]
I can confirm this. Once the shield gets down and you interrupt the cast from any of the two Val'kyrs, that specific Val'kyr will stop casting Light Surge/Dark Surge until the rest of the encounter.
Info has been taken directly from the World of Logs.

**Comment by Golganeth** [comment]
Thank you for the report.

**Comment by Crispybuilt** [comment]
We've encountered it in 25hc for sure since we keep logs from it. I assume it might be the same on 25n,10n and 10hc as well. We can check tonight and let you know

**Comment by Lothloryen** [comment]
Hello there,

Currently working on it, I did receive a good report about it.

Thank you.

**Comment by Lothloryen** [comment]
Hello again,

This issue has been corrected already, It will be deployed to Algalon with the next scheduled maintenance, which I expect to perform tomorrow's morning (not 100% sure - if not, it will be done the Friday's morning).

Thank you very much, really appreciated.

**Comment by hAkonf** [comment]
Still broken. Surges stopped 2 minutes (light surge) and 1 minute (dark surge) before encounter was killed.

**Comment by Lothloryen** [comment]
Hello HAkonf,

I just got an e-mail about it and thank you for reporting it - let me take a look about what could happened. It seems like a very weird issue, on a testing environment it works perfectly now after applying the fixes.

Will try to keep you updated.

**Comment by hAkonf** [comment]
Still broken.

**Comment by Lothloryen** [comment]
I will deploy a correction during the following days, feedback will be appreciated.

Thank you very much.

**Comment by Lothloryen** [comment]
Hello again,

I will try to deploy this correction tomorrow Monday - I have not been able by any means to reproduce the issue with this fix. If you do, please let me know if you did something special.

Thank you.

**Comment by hAkonf** [comment]
This happens literally every time we do ToGC25. You get the shields, interrupt them, and after that the surges just stop ticking completely. So after 2 shields there are no surge dmg at all.

**Comment by hAkonf** [comment]
If you want to see it in action you can just spectate any raid today (read: Obsidius and Death Wish)

**Comment by Lothloryen** [comment]
No no, I meant after this fix - I know which is the issue. I am not able to reproduce it after the correction (which I will try to deploy tomorrow). I want to know if it is also corrected on a real raid player environment.

Thank you.

**Comment by hAkonf** [comment]
Gotcha.

**Comment by hAkonf** [comment]
Confirmed it works now. Cheers.

**Comment by Lothloryen** [comment]
Thank you very much, really appreciated the feedback - the weird issue with Jaraxxus was also corrected, hopefully, no one shall experience it anymore under any circumstance.
