### ISSUE TITLE
Captain Melrache does not spawn

### ISSUE THREAD

**Issue by danisipos92** [dalaranwow/dalaran-wow#3499]
**Description**: During the "At War with the Scarlet Crusade" quest with the Undead Warlock, it can be noticed that one of the NPC's that the quest requires to be killed, specifically Captain Melrache, does not spawn and therefore the quest cannot be completed.

**Current behaviour**: The issue occurs in Tirisfal Glades, at the Scarlet Outpost in the north-west corner of the map. Wowhead.com provides the coordinates 79.4 25.4 for Captain Melrache. 

When the user arrives at the Scarlet Outpost located at 79.4 25.4, it can be noticed that the NPC Captain Melrache, required for the completion of the quest, does not spawn. I have waited there for Captain Melrache to spawn for as long as it was needed for the other NPC's there to be spawned three times.
In other words, other NPC's on location spawned three times during my wait and Captain Melrache didn't spawn once.

**Expected behaviour**: He should spawn, specifically next to the two Bodyguard NPC's located inside the Scarlet Outpost.

**Steps to reproduce the problem**:

1. Acquire quest from Executor Zygand in Brill.
2. Reach the Scarlet Outpost located in the north-west corner of the map.
3. Enter the Scarlet Outpost and dispose of the two Bodyguards.
4. Notice that Captain Melrache isn't present (and i'm fairly certain won't be until this issue is fixed).

The coordinates provided by wowhead.com place Captain Melrache at 79.4 25.4 in Tirisfal Glades, located inside the Scarlet Outpost.

I have attached several screenshots in which it can be noticed that even though the Bodyguards do spawn as intended, Captain Melrache doesn't.
![wowscrnshot_062516_122808](https://cloud.githubusercontent.com/assets/20139277/16355988/12911f5c-3ad2-11e6-9fdd-50ad06ec7207.jpg)
![wowscrnshot_062516_122813](https://cloud.githubusercontent.com/assets/20139277/16355989/1291f44a-3ad2-11e6-9559-560fd8945517.jpg)
![wowscrnshot_062516_122906](https://cloud.githubusercontent.com/assets/20139277/16355990/1292a3d6-3ad2-11e6-9681-d4dc793ab8b0.jpg)

**Comment by Golganeth** [comment]
It dropped slightly below the ground, general issue with pathfinding and NPCs. It's fixed now in-game.
Feel free to open an in-game ticket in case you may encounter something similar again in the future.

Closed.

**Comment by LarisaAdriana** [comment]
This issue is still occurring in the WoTLK 3,3,5a. Captain Merlache is spawned underneath the floor. But the quest can be completed by all the characters that have a minion (eg: Warlock) by ordering the pet to attack him.
![wowscrnshot_072016_222531](https://cloud.githubusercontent.com/assets/20565061/17000168/f20c3440-4ec9-11e6-96f1-e07a0442febb.jpg)
![wowscrnshot_072016_222538](https://cloud.githubusercontent.com/assets/20565061/17000169/f20ce1d8-4ec9-11e6-9b27-276d92726535.jpg)
