### ISSUE TITLE
Pet follow movement

### ISSUE THREAD

**Issue by akutx** [dalaranwow/dalaran-wow#3800]
I am quite surprised that no one brought this up, the Hunter pet is completely out of order, for example the size of the pet is not as it should be: the pet is too small, second issue is the pet runs behind it's master like 6-7 yards away when it should actually run side by side with the hunter. i mean if you were able to recreate a whole world of warcraft you can make more effort to make it feel blizzlike, i bet it's not hard making it happen and fix the hunter pet with a little more effort !
thank you :)
![wowscrnshot_110216_022929](https://cloud.githubusercontent.com/assets/23203712/19914252/2aa69e4a-a0a9-11e6-9d0f-41795598fdf8.jpg)

**Comment by robinsch** [comment]
On PTR. Commit message: Implement Pet follow movement to use player position extrapolation. Implement pet orientation synchronizing with owner when following.

**Comment by akutx** [comment]
i don't know how to do that!

**Comment by Rushor** [comment]
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by tripleslash** [comment]
Not working on live server. Ghoul is still not moving next to me, but rather 10 yards behind me.

**Comment by robinsch** [comment]
This is not even on PTR.

**Comment by Lothloryen** [comment]
My bad, read it quickly, thought it was https://github.com/dalaranwow/principal/commit/4251dbf75c9855862d97f57012717462d3a8d029

**Comment by TeridanDW** [comment]
Hello, not sure here, but I don't think this is the intended result (remember testing this on the old ptr and it worked much better there).
![image](https://user-images.githubusercontent.com/6797611/32489195-d20cb75a-c3b7-11e7-9b22-dac84a2f1a3d.png)
