### ISSUE TITLE
[Druid] Force of Nature: Treants, when summoned, won't attack hostile target!

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#3867]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: The treants summoned by Force of Nature do NOT engage in combat with the target.

**Current behaviour**: When casting Force of Nature on top of a target with which I'm engaged in combat (or near them), the 3 summoned treants, even though they're on aggressive mode, won't attack unless I click on the attack command (or press ctrl+1).

**Expected behaviour**: When Force of Nature is casted on top of a hostile target, the summoned treants should directly engage in battle with the target, especially when they're on aggressive mode.

**Steps to reproduce the problem**:

1. Engage into combat with a mob or a boss.
2. Cast Force of Nature on top of it (or near them)
3. Notice the behavior of the treants

**Include the ID for the spell**: Force of Nature: 33831

**Include Screenshots from the issue if necessary**: http://imgur.com/PJGckrU
As you can see in the screenshot, the treants are already summonded, I'm already in combat but they don't attack unless I click on the attack command (or press ctrl+1). Even on recount they don't show up (additional proof: http://imgur.com/pBFB6kq here they show on recount because I summoned them and clicked on the attack command).

**Comment by Rushor** [comment]
creature_scripts is needed here

**Comment by Rushor** [comment]
Scripts/Pets: Treants- Directly attack selected target of the owner after summon, if the owner attacks the target

* closes https://github.com/dalaranwow/dalaran-wow/issues/3867

![GitHub Logo](http://i.imgur.com/W1Y9Fdz.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Edzero** [comment]
Druid Treants now automatically attack the Druid's target after being summoned.

However they do not defend their owner or themselves if they are put into Defensive Stance. If they are in combat with an enemy when the player switches them from Aggressive to Defensive, they will continue to attack that target until the target dies but will not react to any further attacks against themselves or their owner.

**Comment by TeridanDW** [comment]
Hello after few tests on PTR:

 - Everything said by @Edzero is still happening.
 - Treants seems to assist their master only in pve and when the target is aggresive, meaning vs dummys they don't assist (unless the master is autoattacking the dummy).
 - In PvP they don't assist their master unless he is attacked by spell "auto attack"  or the master attacks with spell "auto attack" from melee or range distance.
spell "auto attack"https://wowgaming.altervista.org/aowow/?spell=6603
