### ISSUE TITLE
[Death Knight] [Skills] Raise Dead

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3897]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 Sometimes Raise Dead bugs out, not summoning the ghoul, and forever staying in cd until the player relogs. Also, sometimes it's cooldown is refreshed to 0 when the player relogs.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 Sometimes it does not summon the ghoul, bugging the CD also.
 Sometimes it's cd is auto-reseted upon relogging.

**Expected behaviour**: Tell us what should happen instead
 It should not bug out.
 It should not reset it's cd upon relog.

**Steps to reproduce the problem**:

1.  Use the skills alot of times.
2.  Observer the minor glitches.
3. 

**Include proofs for this behaviour**

https://postimg.org/gallery/2n9md6mku/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/1d627ca1ea2e5bc15907ab9b81bf3f03f9effb36

**Comment by TeridanDW** [comment]
Most of the issues regarding this report are indeed fixed, however there is still a senario in which the cooldown of the spell get stucked.
If the player has talent http://wotlk.openwow.com/spell=52143 it's not possible to "bug" the cooldown of the spell (according to my tests).
If the player doesn't have that talent it is possible to "bug" the cooldown by:
 - summon the pet
 - get teleported somewhere (far) by using hearstone, rdf, rbg, arena, summoning and so on.

On arrival the cooldown will still be greyed out and will change on relog.
Possible reason for that is that the pet is not summoned on the new location of the player (this happens when the player has the talent http://wotlk.openwow.com/spell=52143)

**Comment by Rushor** [comment]
if the player does not have the talent the pet should be unsummoned. That was fixed in https://github.com/dalaranwow/dalaran-wow/issues/1815 and should solve the mentioned issue (waiting for ptr update)

**Comment by TeridanDW** [comment]
Ok, will consider these 2 reports as separete ones (even though they are linked).

> this was fixed with TrinityCore/TrinityCore@1d627ca

 For this issue will set:

**Comment by critbit** [comment]
This is not fixed on Algalon, as an UH DK with Master of Ghouls there's still a bug causing the pet to be unable to be summoned after it dies, but not putting the spell on CD as the game thinks the pet is active. When trying to use it again you just get the error message 'Ability not ready yet.' 

Not sure what causes the bug but if it helps it most often happens in duels when the pet is killed/sacrificed.

**Comment by Rushor** [comment]
Ref: 
https://github.com/TrinityCore/TrinityCore/commit/ecbbcc8972f43376c65cb726c37cf777ee968f66
https://github.com/TrinityCore/TrinityCore/commit/f012800751396309e75d0baf4ed3406855c8e93a
