### ISSUE TITLE
[Quest][Classic] Craftsman's Writ

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4145]
**Current behaviour**: The quest "Craftsman's Writ" is not repeatable.

**Expected behaviour**: The quest "Craftsman's Writ" should be repeatable.

**Steps to reproduce the problem**:

1. Go to Eastern Plaguelands and talk to "Dispatch Commander Matz", finish the quest "They Call Me "The Rooster"" and then complete the next quest "Craftsman's Writ".
2. Notice that he doesn't offer you the quest again.

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Quest:Craftsman%27s_Writ

**Comment by Rushor** [comment]
DB/Quest: Craftsman's Writ - Should be repeatable

* closes https://github.com/dalaranwow/dalaran-wow/issues/4145
* commit: 73a87d75a660de3b447017296128c6f997347304

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Klala** [comment]
Contrary to what the changelog says, this quest is still not repeatable. Reopen this issue.
