### ISSUE TITLE
[NPC][Classic] Amani Berserker  - wrong spelluse

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4430]
Creature currently uses http://www.wowhead.com/spell=8269/frenzy - increases attack speed by 60%.

It appears the correct spell is actually http://www.wowhead.com/spell=8599/enrage - increases attack speed by 30% and damage by 10%.

Evidence:
http://www.wowhead.com/spell=8599/enrage#used-by-npc
http://www.wowhead.com/npc=15643/amani-berserker#comments:id=196890

**Comment by Rushor** [comment]
DB/Creature: Amani Berserker - Now uses the correct Frenzy spell

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4430
* commit: 06f026e124c9b523b0e8c9eabd49399b08681791

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by warcraftgeekygamer** [comment]
@Rushor 

As of August 1, 2017, this is still an issue. NPC #15643 is casting http://www.wowhead.com/spell=8269/frenzy - which increases attack speed by 60%.

It appears the correct spell is actually http://www.wowhead.com/spell=8599/enrage - increases attack speed by 30% and damage by 10%.

Evidence:
http://www.wowhead.com/spell=8599/enrage#used-by-npc
http://www.wowhead.com/npc=15643/amani-berserker#comments:id=196890
