### ISSUE TITLE
[Priest][Spell] Improved Devouring Plague

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4678]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)
Similar issue to https://github.com/dalaranwow/dalaran-wow/issues/4575. (But not identical).
If it was fixed with the same commit I apologize.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Improved Devouring Plague does too much damage when the target has a damage modifier debuff, but not when the debuff is on the player.

**Expected behaviour**: Tell us what should happen instead
Improved Devouring Plague should not do 4x normal damage with a 100% modifier, it should do 2x.

**Steps to reproduce the problem**:
1. Play shadow priest on beasts to confirm too high damage, and on twins to confirm working as intended.
2. Use Devouring Plague with different damage modifiers active (Staggered Daze, Essence / Empowered).
3. Observe Improved Devouring Plague damage.

**Include proofs for this behaviour**
**Northrend Beasts Dalaran (2017-04-10):**
http://www.worldoflogs.com/reports/a2nfhifmzm2tlj4w/log/?s=307&e=694
`[{"spellNames": ["Staggered Daze"]}, {"spellNames": ["Improved Devouring Plague"], "eventTypes": [1], "sourceNames": ["Svarteman"]}]`
![http://i.imgur.com/vJCe4ej.png](http://i.imgur.com/vJCe4ej.png)
Damage is 4x normal damage with a 100% modifier (Staggered Daze). 2x expected.

**Northrend Beasts LIVE (2010-01-28):**
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=1766&e=2151
`[{"spellNames": ["Staggered Daze"]}, {"spellNames": ["Improved Devouring Plague"], "eventTypes": [1], "sourceNames": ["Evaelyn"]}]`
![http://i.imgur.com/fsCAvRq.png](http://i.imgur.com/fsCAvRq.png)
Damage is 2x normal damage with a 100% modifier (Staggered Daze). As expected.

**Including Twins aswell, although it seems to work as intended here. Maybe due to it being a player debuff and not a target debuff?**

**Twin Valkyrs Dalaran (2017-04-10):**
http://www.worldoflogs.com/reports/a2nfhifmzm2tlj4w/log/?s=2332&e=2575
`[{"spellNames": ["Empowered Darkness"], "targetNames": ["Svarteman"]}, {"spellNames": ["Empowered Light"], "targetNames": ["Svarteman"]}, {"spellNames": ["Improved Devouring Plague"], "eventTypes": [1], "sourceNames": ["Svarteman"]}]`
![http://i.imgur.com/RGeKbiH.png](http://i.imgur.com/RGeKbiH.png)
Damage is correct when damage modifier is on the player (and not on the target).
It does around 5k with no damage modifiers, and here it does around 8k with a 50% modifier (Dark Essence/Light Essence).

**Twin Valkyrs LIVE (2010-01-28):**
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=4120&e=4309
`[{"spellNames": ["Empowered Darkness"], "targetNames": ["Evaelyn"]}, {"spellNames": ["Empowered Light"], "targetNames": ["Evaelyn"]}, {"spellNames": ["Improved Devouring Plague"], "eventTypes": [1], "sourceNames": ["Evaelyn"]}]`
![http://i.imgur.com/weh2Osx.png](http://i.imgur.com/weh2Osx.png)
Damage is what you would expect here aswell. 4k for this player normally, and around 6k here with a 50% modifier (Dark Essence/Light Essence).

http://www.worldoflogs.com/guilds/573/calendar/01-10/ To confirm live log is from live.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/spell=65684/dark-essence
http://www.wowhead.com/spell=65686/light-essence
Improved Devouring Plague 63675 (openwow down atm)
Staggered Daze 66758
Empowered Light 67218
Empowered Darkness 67215

**Comment by Rushor** [comment]
Game/Spells: Improved Devouring Plague - Disable extra damage bonus

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4678
* commit: a9c819cf7145b8412f9bbd25bf2c6b6a990657ae

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
I have done some tests on PTR for this issue in ToC 10 with 
Improved Devouring Plague 63675 and Staggered Daze 66758 and the extra damage bonus is still present.
My stats:
![wowscrnshot_101317_171833](https://user-images.githubusercontent.com/6797611/31550687-d2c76b4e-b03a-11e7-8138-6c422fb9d336.jpg)

Damage without Staggered Daze
![wowscrnshot_101317_171041](https://user-images.githubusercontent.com/6797611/31550738-fcc5dcaa-b03a-11e7-8006-e3801fa74943.jpg)

Damage with Staggered Daze
![wowscrnshot_101317_171027](https://user-images.githubusercontent.com/6797611/31550751-0ae98782-b03b-11e7-8bb8-73564f73c097.jpg)

So reopening.

**Comment by robinsch** [comment]
Waiting for PTR Update.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
![wowscrnshot_101617_112050](https://user-images.githubusercontent.com/6797611/31601934-2239ea78-b264-11e7-81f7-f63162be1c2b.jpg)
![wowscrnshot_101617_112044](https://user-images.githubusercontent.com/6797611/31601937-2499b71c-b264-11e7-8e62-3eaee5ea0322.jpg)

**Comment by Lothloryen** [comment]
#4910 

Fixed with https://github.com/dalaranwow/principal/commit/d3a5a858f486ace1f88e34d97b4e77fd82a04265

On Live server already.
