### ISSUE TITLE
[Mage] Mages damage themselves with their own Arcane Missiles while channeling other spells.

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#4709]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Currently, while casting Arcane Missiles at something, if target dies for whatever reason before the cast was finished a small array of interesting side effects will occur: 

* mage tries to finish the cast animation and points their hand convulsively at dead target.
* if they try to use any channeled spell while doing the above, remaining missiles will actually damage the mage. This damage will not reduce channeling duration. Also, this damage can crit as any regular missile.

**Expected behaviour**: Tell us what should happen instead

Obviously, mages shouldn't damage themselves with their own missiles, nor they should try to cast any remaining missiles if their target died before the missile cast was finished.

**Steps to reproduce the problem**:

1. Get any world mob to 1% hp or so.
2. Cast Arcane Missiles at it. Kill it in a way that there are few missiles yet to cast after it's dead (so the mage will point a hand at dead target trying to finish the cast).
3. **Immediately** after a mob drops dead begin casting any channeled spell (e.g. Evocation), watch as remaining missiles will damage the mage herself.

**Include proofs for this behaviour**

Patch 1.12.0 (2006-08-22): It is no longer possible to cast Arcane Missiles on an evading mob. **In addition, the animation will now stop when the target is dead.**

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wow.gamepedia.com/Arcane_Missiles

**Include Screenshots from the issue if necessary**

![wowscrnshot_051317_231215](https://cloud.githubusercontent.com/assets/8515510/26041385/1bb3537c-3935-11e7-953b-d2768139cc10.jpg)

![wowscrnshot_051417_165806](https://cloud.githubusercontent.com/assets/8515510/26041389/21c7723e-3935-11e7-98c1-5152fd2851c9.jpg)

![wowscrnshot_051517_043203](https://cloud.githubusercontent.com/assets/8515510/26041396/291a6cbc-3935-11e7-94d3-c7dae690be8a.jpg)

![wowscrnshot_051517_054208](https://cloud.githubusercontent.com/assets/8515510/26041401/310359f2-3935-11e7-8efc-cb230e7a046b.jpg)

Cheers.

**Comment by n-ghost** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2259

Might or might not be related.

**Comment by TeridanDW** [comment]
Hello @n-ghost , thank you for the report.
I'm currently unable to test this issue myself but the screenshots are good proof so I'll add the label.
Also #2259 seems relevent to me too.

**Comment by Rushor** [comment]
Scripts/Spells: Mage - Arcane Missile - Do not target the caster itself 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4709
* commit: 8305cb2d2c0f91d13345e91afbb0ccb025fdebc2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR the results are:
Issue:

>  - mage tries to finish the cast animation and points their hand convulsively at dead target.

is still happening.

![image](https://user-images.githubusercontent.com/6797611/31884035-83a137e0-b7f4-11e7-8913-7b59a18be02f.png)

> -  if they try to use any channeled spell while doing the above, remaining missiles will actually damage the mage. This damage will not reduce channeling duration. Also, this damage can crit as any regular missile.

is still happening. 
Steps to reproduce it:
1. Target a creature and cast spell https://wowgaming.altervista.org/aowow/?spell=42846.
2. Creature dies from first "tick" of the spell.
3. Cast spell https://wowgaming.altervista.org/aowow/?spell=12051 instantly after the creature dies.
4. Notice the rest of the missles will hit the mage himself.

![image](https://user-images.githubusercontent.com/6797611/31884437-ada53e78-b7f5-11e7-8a83-9688520b3ce1.png)


I will add 1 from me:
 - Spell https://wowgaming.altervista.org/aowow/?spell=42846 has no effect on critters (it seems it's instantly interupted on cast but animation (player only) continues).

![image](https://user-images.githubusercontent.com/6797611/31884105-bf44396e-b7f4-11e7-9d13-18891c181889.png)
