### ISSUE TITLE
[ICC] - gunship only drops two pieces of loot on 25 man

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4736]
Gunship fight on 25 man normal only drops 2 pieces of loot instead of 3. Don't know about 25 hc, if someone knows please comment.

http://www.wowhead.com/object=201873/gunship-armory

**Comment by StheNoble** [comment]
i also wondered about this since all other bosses drop 3 in there.

I couldnt find any written proof pro 3 pieces for now, but i could find kinda proof on many "how to solo" videos from later expansions where you can clearly see 2 drops in 10 and 3 in 25 on GS Battle.

http://www.youtube.com/watch?v=rLcZHqlQiVY
10M hc. 2pc

https://www.youtube.com/watch?v=PulGeTbRzEo
https://www.youtube.com/watch?v=Vb7tcWKxHu8
25m normal - 3 pieces

**Comment by alexuktc** [comment]
Noticed this as well. Really hope it can be fixed (along with adding loot groups for the boss - we had 2 healing trinkets drop from it last week which should simply not be possible) before raid lockout reset.

**Comment by Winstrol** [comment]
same on heroic

**Comment by Rushor** [comment]
DB/Loot: ICC gunship chest should contain 3 items in 25 NH+25HC

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4736
* commit: e6785f813512ce07ccf54f75dbe0fb2313344481

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Asdafat** [comment]
@Lothloryen Will this be fixed on the live servers soon? Issue still exists

**Comment by datbunneh** [comment]
@Lothloryen @Rushor @TeridanDW Can this fix be deployed please cause it's quite a biggie?

**Comment by Lothloryen** [comment]
Hello there, deployed already. Will change labels a bit later.

**Comment by datbunneh** [comment]
@Lothloryen Thanks.
