### ISSUE TITLE
[Quest][Northrend] At The Enemy's Gates

### ISSUE THREAD

**Issue by thestranger064** [dalaranwow/dalaran-wow#4752]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Linking to 2 closed ones that is being ignored. 
https://github.com/dalaranwow/dalaran-wow/issues/2713
https://github.com/dalaranwow/dalaran-wow/issues/2410

**Current behaviour**: The Boneguard Footman does not die when running over the horse with them. 

**Expected behaviour**: They should be killed as soon as you run over them.

**Steps to reproduce the problem**:

Get the Daily quest At The Enemy's Gates
2. Run over the Boneguard Footman with your horse.
3.  Observe they are still alive

**Include proofs for this behaviour**

http://imgur.com/a/KEuYk screenshots on the footman.

http://wotlk.evowow.com/?npc=33438
http://www.wowhead.com/npc=33438/boneguard-footman#comments:id=886280

**Include Screenshots from the issue if necessary**

Note: Stop closing issues that is not fixed. Remember we testers also spend and taking our time reporting this. If you dont want to fix these problems tell us ingame, or on the wow-dalaran.com that you are no longer interested in our bug reports. We are doing this to help out, no matter how small or big the issue is.

**Comment by Rushor** [comment]
> Stop closing issues that is not fixed. Remember we testers also spend and taking our time reporting this. If you dont want to fix these problems tell us ingame, or on the wow-dalaran.com that you are no longer interested in our bug reports. We are doing this to help out, no matter how small or big the issue is.

No once the issue was closed with the label "waiting for ptr update" it means following:

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Game/Spells: Add spellscriptsupport for quest 'At the Enemy's Gates'

* Trample Scourge spell now only targets the footmans
* spell 'Trample Scourge' 63001 will now periodically trigger spell 'Trample Scourge' https://wowgaming.altervista.org/aowow/?spell=63001 (damage effect)
* player vehicles for the quest now get faction 2105 (friendly to player, agressiv to monster)
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4752
* commit: 1747c62568421b34954fc6d78e6b7e92e78cd0ad

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by thestranger064** [comment]
Hello as of today 02-26/2020 - 2 years later this is still not implented

**Comment by Golganeth** [comment]
Still an issue.
