### ISSUE TITLE
Val'anyr fragments drop rate (Ulduar 25)

### ISSUE THREAD

**Issue by Tracker4you** [dalaranwow/dalaran-wow#4997]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
On my last 2 runs only one fragment drop (no Yogg 100% drop too)
**Expected behaviour**: Tell us what should happen instead
All bosses should have 40% drop rate on Normal mode (little bit more on Hard mode)
**Steps to reproduce the problem**:
1. Just rewrite drop rate for fragments on each boss (40%)
2. 100% drop on Yogg
3. 

**Include proofs for this behaviour**
Whole Dalaran-WoW server will say drop is not right.

**Comment by alexuktc** [comment]
40% normal and 60% Hard mode.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Tracker4you.
Regarding:

> On my last 2 runs only one fragment drop (no Yogg 100% drop too)

this is addressed here #2247 (I've added a label).

And:

> Just rewrite drop rate for fragments on each boss (40%)
> 40% normal and 60% Hard mode.

could you provide any proof for these %s as wowhead says it should be less http://www.wowhead.com/item=45038/fragment-of-valanyr
Thank you.

**Comment by alexuktc** [comment]
Ah, don't take my word for it. I heard that from guildies farming it. I do not use a class that can use it so I never bothered to really get informed.

**Comment by Tracker4you** [comment]
Ty for respond... I know it is adressed but still not fixed ( even Yogg 100% drop) almost 2 year ago reported
You can't compare those drops from new Legion patch (Cuz that drop is for Legion now, not WoTLK)
AtlasLoot Enchanched v5.11.04 ( Dedicated addon for items WoTLK 3.3.5a ) show this:

https://imgur.com/a/A4LyU

**Comment by StheNoble** [comment]
This addons drop chances are plainly wrong in many cases.

Here are some numbers from wow wiki from 2009 during retailtime:
http://wowwiki.wikia.com/wiki/Fragment_of_Val%27anyr?oldid=2128376
