### ISSUE TITLE
Quest: Saragosa's End

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#546]
http://www.wowhead.com/quest=11957/saragosas-endSaragosa isnt weakened, doing aprox 2k dmg in platers. Also after turning in the quest Keristrasza dosnt offer a teleport back to Amber ledge
http://www.wowhead.com/npc=26206
http://www.wowhead.com/spell=46824

**Comment by taralej90** [comment]
Still not fixed.

**Comment by Lebaowski** [comment]
As the quest is now, Saragosa's spawned in the middle of the sky, in her human form. When teleported by Keristrasza you get to an empty platform, but while flying towards Transitus Shield(Coldarra base), you will see Saragosa fall through the sky and land on the ground below.

She's unattackable due to 'out of range' in this position, making the quest practically impossible to complete unless this is different just after a server restart. Will check next reset and report back if it works then.

**Comment by Lothloryen** [comment]
Hello there,

This quest was already corrected.

Thank you for the reports.

**Comment by Anecho** [comment]
Not working again.
Saragosas landing event isn't triggered. Getting teleported to an empty platform.

**Comment by Imbarawr** [comment]
@Lothloryen the issues are still there with this quest, making it impossible to complete. Like Lebaowski said, she falls down and stands on the ground. You can not attack her, out of range it says. The platform where she should be is empty.

Screenshot of her on the ground: https://i.imgur.com/tYmpTOi.jpg

Don't know if this issue is fixed yet or not or if it's needed to post about it here but I figured rather safe than sorry and let you know.

**Comment by TeridanDW** [comment]
Works as intended for me on PTR.
