### ISSUE TITLE
Quest: Green Technology

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#693]
http://wotlk.openwow.com/quest=13379

**Issue:** Once you pick up the quest, "Infra-green Vision" is not casted on you. On top of that, the NPCs on the platform where you have to hand in the quest are not spawned, and the zone misses his protecting shield.

**How it should work:** Once you pick up the quest, "Infra-green Vision" should be casted on you, and the NPCs on the platform should become visible once you get inside the protecting shield.

-----------------------

- *Fringe Engineer Tezzla* - http://wotlk.openwow.com/npc=32444
- *Infra-green Vision* - http://wotlk.openwow.com/spell=59651
- ***Alliance Version*** - #688

**Comment by Anecho** [comment]
As Golganeth said:

> **Quest is doable but not in a proper way**

Wouldn't mind sharing the way on how to do it? I personally can't reach NPC to turn in that quest.

**Comment by ashido96** [comment]
As the last comment was almost 2 years ago, I'll throw out a mention that this is still bugged as described above.
As well as that there is no visual 'greenish?' bubble around either of the two platforms for both alliance and horde.

**Comment by DrFuler** [comment]
[21/04/2016] - Seems to be still bugged.

**Comment by Cone182** [comment]
still bugged, no green vision.

**Comment by jonanone** [comment]
Tezza is now spawned and visible to everyone. This quest is now doable but not yet finished since infra-vision buff is still missing. It allows to follow with the next quests on the chain.

**Comment by Lothloryen** [comment]
#759

**Comment by MrAndersonX** [comment]
The NPC is not spawned. So, you cannot talk to her/take the quest/complete the chain. Still bugged. Bump.

https://postimg.org/gallery/1pdfa1b7o/

**Comment by Rushor** [comment]
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


@MrAndersonX: please fill the informations on this in the ticket #759

**Comment by TeridanDW** [comment]
> Tezza is now spawned and visible to everyone. This quest is now doable but not yet finished since infra-vision buff is still missing. It allows to follow with the next quests on the chain.

Tezza is not visible (not there at all), please continue with this issue in #759

**Comment by ScarletPoem** [comment]
Can confirm, NPC Tezza is still not visible, therefore cannot complete this q.
