### ISSUE TITLE
Charmed creatures by quest items

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#775]
Upon charming, controlling a creature as pet everything is fine until the player gets in combat, the effect brokes and the creature resets ( reseting the faction flags) 
With this bug, some quests are not doable or hardly doable
Example: Zero Tolerance - www.wowhead.com/quest=12686

**Comment by MrAndersonX** [comment]
Confirmed - Zero Tolerance - bugged. Needs a fix.

**Comment by darksinge** [comment]
Just tried this quest, still bugged... super frustrating because there is no progressing this quest line past this point.

**Comment by jonanone** [comment]
Zero tolerance charming has been fixed and now it will be usable against Darmuk.
The fix will be applied to the live realm soon.

**Comment by MrAndersonX** [comment]
The fix still hasn't been applied. So it still needs to be implemented.

**Comment by Raulfin** [comment]
Issue persists during quest Zero Tolerance and the follow up, Fuel for the Fire.
