### ISSUE TITLE
NPC: "Sky-Reaver Korm Blackscar" and "Koltira Deathweaver"

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#907]
Current issue:
These two NPCs on the ship Orgrim's Hammer tend to drop out, not be present, making it unable to quest properly.

First occasion was when I first arrived at the ship to turn in the quest that I got in Dalaran, the Sky-Reaver was missing. Then also Koltira wasn't present, popped there when I flew back to ship sometime later. Then later when I went to turn in quest "Orgrim's Hammer" at Sky-Reaver, I turned it in but before I could take the next quest, he started sliding out of the ship backwards, till he disapeared. Also later I saw Koltira float near ground.

http://www.wowhead.com/npc=30824 - Sky-Reaver Korm Blackscar
http://www.wowhead.com/npc=29795 - Koltira Deathweaver

**Comment by thisischaos** [comment]
Still an issue. I picked up some quests with no issue at all, but when I came back to turn them in; none of the quest NPC's were there.

**Comment by AgeAgainst** [comment]
Can confirm - unable to see any quest givers on Ogrim's Hammer.  Stayed on the ship a full rotation of it's path looking for quest mobs - none.  This is preventing me from opening up Ebon Hold questline and all the npcs at The Shadow Vault are red to me.

**Comment by aepoirier** [comment]
I was able to see all the npc's on Ogrim's Hammer. After a small delay with no visible npc's, after ~ 5 seconds all npc's were accounted for. However, when clicking on Sky-Reaver Korm Blackscar to turn in a quest (The very first quest I got for Icecrown, from the npc in Krasus' Landing in Dalaran) his gossip window will not open and I am unable to turn the quest in, or gather any that he gives out later in the quest chain.

**Comment by Rushor** [comment]
Dropping below transports was fixed for npcs long time ago

**Comment by roblockster** [comment]
> However, when clicking on Sky-Reaver Korm Blackscar to turn in a quest (The very first quest I got for Icecrown, from the npc in Krasus' Landing in Dalaran) his gossip window will not open and I am unable to turn the quest in, or gather any that he gives out later in the quest chain.

This issue is still occurring. Players are usually unable to interact with this NPC.

**Comment by thanhtotti** [comment]
I encounter this bug today. Can't find Sky-Reaver Korm Blackscar to turn in the quest Orgrim's Hammer
